### ISSUE TITLE
Consumer group API writes invalid user_data field

### ISSUE THREAD

**Issue by samstokes** [zendesk/ruby-kafka#164]
I have an app using ruby-kafka 0.3.2 to consume from a Kafka 0.9.0.0 broker.  When I use the `kafka-consumer-groups.sh` admin script provided with the Kafka 0.9.0.0 distribution, e.g. to check the lag of the consumer group, I get the following error:

```
$ ~/opt/kafka/bin/kafka-consumer-groups.sh --new-consumer --command-config client-ssl.properties --bootstrap-server my-broker:9096 --describe --group searchify-1
Error while executing consumer group command Error reading field 'user_data': java.lang.IllegalArgumentException
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'user_data': java.lang.IllegalArgumentException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:71)
	at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeAssignment(ConsumerProtocol.java:109)
	at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:165)
	at kafka.admin.AdminClient$$anonfun$describeConsumerGroup$1.apply(AdminClient.scala:164)
	at scala.collection.immutable.List.map(List.scala:273)
	at kafka.admin.AdminClient.describeConsumerGroup(AdminClient.scala:164)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describeGroup(ConsumerGroupCommand.scala:314)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$class.describe(ConsumerGroupCommand.scala:84)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describe(ConsumerGroupCommand.scala:302)
	at kafka.admin.ConsumerGroupCommand$.main(ConsumerGroupCommand.scala:63)
	at kafka.admin.ConsumerGroupCommand.main(ConsumerGroupCommand.scala)
```

We have verified that the broker logs don't contain any errors corresponding to this error, so it seems like the broker is returning a response that the admin tool can't parse.  I haven't dug into the source of `kafka-consumer-groups.sh` yet, but it seems like the ruby-kafka consumer group implementation may be setting some metadata in a way that trips up the admin tool?

I don't think it's a problem with the `kafka-consumer-groups.sh` script communicating with the broker, because the `--list` option works, with the same configuration:

```
$ ~/opt/kafka/bin/kafka-consumer-groups.sh --new-consumer --command-config client-ssl.properties --bootstrap-server my-broker:9096 --list
searchify-1
```

**Comment by samstokes** [comment]
P.S. my consumer setup code looks like this:

```ruby
kafka = Kafka.new({
  seed_brokers: kafka_brokers,
  logger: logger,
}.merge(kafka_ssl_opts))
@consumer = kafka.consumer(group_id: kafka_consumer_id)
kafka_topics.each {|topic| @consumer.subscribe(topic) }
```

**Comment by dasch** [comment]
i think that field is supposed to be defined by the client implementation, so the tool may be making too many assumptions. I'll try to take a look as soon as I have time.

**Comment by dasch** [comment]
Hmm. According to the [protocol spec](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol), the UserData field is supposed to be opaque to Kafka. I think the CLI tool is overstepping its bounds, assuming that the official consumers are used...

**Comment by dasch** [comment]
Could you try to patch https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/protocol/member_assignment.rb#L28 and write some string rather than nil and see if that fixes the problem?

**Comment by samstokes** [comment]
Hi @dasch thanks for taking a look at this!  I tried patching `member_assignment.rb` to write `@user_data || 'hello, world'`, and now the script gets a bit further, but still borks:

```
$ ~/opt/kafka/bin/kafka-consumer-groups.sh --new-consumer --command-config client-ssl.properties --bootstrap-server my-broker:9096 --describe --group searchify-1
GROUP, TOPIC, PARTITION, CURRENT OFFSET, LOG END OFFSET, LAG, OWNER
Error while executing consumer group command Error reading field 'responses': Error reading field 'partition_responses': Error reading field 'metadata': java.lang.NegativeArraySizeException
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'responses': Error reading field 'partition_responses': Error reading field 'metadata': java.lang.NegativeArraySizeException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:71)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:464)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:279)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:303)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:197)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:187)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:157)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.fetchCommittedOffsets(ConsumerCoordinator.java:289)
	at org.apache.kafka.clients.consumer.KafkaConsumer.committed(KafkaConsumer.java:1106)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2$$anonfun$7.apply(ConsumerGroupCommand.scala:323)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2$$anonfun$7.apply(ConsumerGroupCommand.scala:322)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2.apply(ConsumerGroupCommand.scala:322)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService$$anonfun$describeGroup$2.apply(ConsumerGroupCommand.scala:320)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describeGroup(ConsumerGroupCommand.scala:320)
	at kafka.admin.ConsumerGroupCommand$ConsumerGroupService$class.describe(ConsumerGroupCommand.scala:84)
	at kafka.admin.ConsumerGroupCommand$KafkaConsumerGroupService.describe(ConsumerGroupCommand.scala:302)
	at kafka.admin.ConsumerGroupCommand$.main(ConsumerGroupCommand.scala:63)
	at kafka.admin.ConsumerGroupCommand.main(ConsumerGroupCommand.scala)
```

**Comment by dasch** [comment]
@samstokes I'm not sure what I can do about this – the protocol states that these fields are reserved for the client, but it seems that the tooling only works with the implementation in the official Java client. I'm not even sure that implementation has API stability, so I'd rather not have ruby-kafka follow it (and lose the ability to implement my own algorithms.)

What kind of monitoring are you looking for, and is it something that can be provided in other ways? I already have some instrumentation in place, and am planning on adding more. It's mostly a matter of finding a good way of reporting the metrics – we use Datadog with a statsd agent.

**Comment by samstokes** [comment]
Hi @dasch, thanks very much for digging into this.  Definitely seems like it's the Kafka command line tools that are making unwarranted assumptions about the content of those fields.  I guess I should report this as a bug to the Kafka project.

I was basically just trying to get visibility into my consumer group offsets (e.g. how much is this group lagging behind the producer) - I don't know of another way besides kafka-consumer-groups.sh, at least without speaking the consumer group protocol directly as ruby-kafka is doing.  If the ruby-kafka consumer group API provided a way to see its offsets, that would definitely help.  (In fact, is that what `Kafka::ConsumerGroup#fetch_offsets` already provides?)  Even better would be if ruby-kafka included a command-line tool to expose this information, so that I could check up on consumer groups even without making changes to a running application.

**Comment by dasch** [comment]
I think you have two options:

1) subscribe to the ACK notifications being emitted through ActiveSupport Notifications, or
2) read from Kafka topic used to persist the offsets. 

The latter is general purpose and should work regardless of the client being used. I use the former to write e.g. lag metrics to statsd.

**Comment by dasch** [comment]
https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L110

**Comment by jessecollier** [comment]
@dasch do you mind sharing `read from Kafka topic used to persist the offsets.` code that you use?

**Comment by dasch** [comment]
@jessecollier I don't have such code, but it should be possible. However, I think a better option would be to use the Active Support Notification instrumentation I've put in place. Look at the Datadog subscriber in the code base for an example of how that can be done.

**Comment by jessecollier** [comment]
I just wanted to update this thread in case anyone else stumbled upon the same issue.   I was trying to read consumer lag regardless of client using the kafka cli utils. This caused an error for us using ruby-kafka lib + kafka 0.9. 

I didn't know how to implement an offset consumer correctly, so I forked burrow and add some statsd metrics I wanted. You can see the diff here:

https://github.com/linkedin/Burrow/compare/master...jessecollier:master

**Comment by dasch** [comment]
It would be nice if Burrow didn't crash when the user data is different from the Java client's. I think that's where the correct fix should go.

**Comment by swaprks** [comment]
Please change the groupid and try. I faced the same issue and changing the groupid helped me. In my case, props.put("auto.offset.reset", "latest"); was set to latest because of which I guess it is expecting a dynamic groupid. So i changed my groupid to include timestamp in it.
