### ISSUE TITLE
Kafka::UnknownError when calling producer.deliver_messages

### ISSUE THREAD

**Issue by rayjohnson** [zendesk/ruby-kafka#227]
/usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/protocol.rb:50:in `handle_error': Kafka::UnknownError (Kafka::UnknownError)

What is odd is I call it successfully a 1/2 dozen times before and things work.  What can cause UnknownError?  Any suggestions for how I can figure out root cause?

**Comment by dasch** [comment]
Can you give me a full stack trace?

**Comment by dasch** [comment]
This sounds like a bug in the broker - it may return error -1, which basically means "unknown broker error". What's the exact version of Kafka this is happening with, and how can you reproduce the problem?

**Comment by rayjohnson** [comment]
Version is Kafka 0.10 from Confluent release.  Currently only installed on one machine.  Given topic only has one partition.

My code is a loop going over a bunch of data.  Every 10 messages it calls.  When I first reported it it was happening every time on the last message.  When my loop finished - I called deliver_messages one last time and then producer.shutdown.  (So the last deliver_messages only had 6 messages.)  I removed that last deliver_messages since it was redundant anyway and things started to work.

However, today I'm seeing the error again on a larger chunk of data going in.   Here is the full stack trace:

/usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/protocol.rb:50:in `handle_error': Kafka::UnknownError (Kafka::UnknownError)
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/produce_operation.rb:118:in `block in handle_response'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/protocol/produce_response.rb:32:in `block (2 levels) in each_partition'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/protocol/produce_response.rb:31:in `each'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/protocol/produce_response.rb:31:in `block in each_partition'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/protocol/produce_response.rb:30:in `each'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/protocol/produce_response.rb:30:in `each_partition'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/produce_operation.rb:110:in `handle_response'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/produce_operation.rb:99:in `block in send_buffered_messages'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/produce_operation.rb:79:in `each'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/produce_operation.rb:79:in `send_buffered_messages'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/produce_operation.rb:45:in `block in execute'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/instrumenter.rb:21:in `instrument'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/produce_operation.rb:39:in `execute'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/producer.rb:297:in `block in deliver_messages_with_retries'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/producer.rb:289:in `loop'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/producer.rb:289:in `deliver_messages_with_retries'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/producer.rb:239:in `block in deliver_messages'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/instrumenter.rb:21:in `instrument'
	from /usr/local/bundle/gems/ruby-kafka-0.3.8/lib/kafka/producer.rb:232:in `deliver_messages'
	from /usr/src/app/lib/kafka.rb:56:in `generate_message'
	from /usr/src/app/lib/aqua.rb:111:in `block (2 levels) in download_query_results'
	from /usr/local/lib/ruby/2.3.0/csv.rb:1748:in `each'
	from /usr/src/app/lib/aqua.rb:101:in `block in download_query_results'
	from /usr/local/lib/ruby/2.3.0/open-uri.rb:155:in `open_uri'
	from /usr/local/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/local/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /usr/src/app/lib/aqua.rb:94:in `download_query_results'
	from /usr/src/app/lib/zuora_export.rb:53:in `block (2 levels) in start'
	from /usr/src/app/lib/zuora_export.rb:50:in `each'
	from /usr/src/app/lib/zuora_export.rb:50:in `block in start'
	from /usr/src/app/lib/zuora_export.rb:47:in `each'
	from /usr/src/app/lib/zuora_export.rb:47:in `start'
	from ./zuora_export:8:in `<main>'
root@469a820e051c:/usr/src/app#

**Comment by rayjohnson** [comment]
I should add that it fails every time after the exact same number of messages sent.  (I keep processing the same data until I know the entire batch is sent to Kafka.  So the data going through is exactly the same each time it is failing.)

**Comment by dasch** [comment]
Hmm.

1. Have you enable any form of compression?
2. Is the message this is failing with larger than the rest?

The error you're seeing is a generic server error. I'm not sure what's causing it – can you try tailing the Kafka broker log and see what shows up?

**Comment by rayjohnson** [comment]
Took me a bit to get access to the Kafka machine.  Seeing this stack dump in the Kafka logs:
[2016-06-23 07:58:50,966] ERROR [Replica Manager on Broker 0]: Error processing append operation on partition zuora-dev-Payment-0 (kafka.server.ReplicaManager)
kafka.common.KafkaException: 
	at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:159)
	at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:85)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
	at kafka.message.ByteBufferMessageSet$$anon$2.makeNextOuter(ByteBufferMessageSet.scala:357)
	at kafka.message.ByteBufferMessageSet$$anon$2.makeNext(ByteBufferMessageSet.scala:369)
	at kafka.message.ByteBufferMessageSet$$anon$2.makeNext(ByteBufferMessageSet.scala:324)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:30)
	at kafka.message.ByteBufferMessageSet.validateMessagesAndAssignOffsets(ByteBufferMessageSet.scala:427)
	at kafka.log.Log.liftedTree1$1(Log.scala:339)
	at kafka.log.Log.append(Log.scala:338)
	at kafka.cluster.Partition$$anonfun$11.apply(Partition.scala:443)
	at kafka.cluster.Partition$$anonfun$11.apply(Partition.scala:429)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:231)
	at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:237)
	at kafka.cluster.Partition.appendMessagesToLeader(Partition.scala:429)
	at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:406)
	at kafka.server.ReplicaManager$$anonfun$appendToLocalLog$2.apply(ReplicaManager.scala:392)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:392)
	at kafka.server.ReplicaManager.appendMessages(ReplicaManager.scala:328)
	at kafka.server.KafkaApis.handleProducerRequest(KafkaApis.scala:405)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:76)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: failed to read chunk
	at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:433)
	at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:167)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at kafka.message.ByteBufferMessageSet$$anon$1.readMessageFromStream(ByteBufferMessageSet.scala:118)
	at kafka.message.ByteBufferMessageSet$$anon$1.makeNext(ByteBufferMessageSet.scala:153)
	... 35 more

**Comment by rayjohnson** [comment]
Ah ha - yes I was using snappy compression.  Found this issue on Kafka: KAFKA-2308

I turned off snappy compression and things started to work.

Should have look at these logs sooner.  Thanks so much for the hint though.  Certainly helped!

**Comment by dasch** [comment]
Great to see you got it working!
