### ISSUE TITLE
Specs don't run on OS X 10.11.5: docker error

### ISSUE THREAD

**Issue by natesholland** [zendesk/ruby-kafka#238]
If this is a bug report, please fill out the following:
- Version of Ruby: 2.2.3
- Version of Kafka: 0.9.0.0
- Version of ruby-kafka: 0.3.9 (master)

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.
###### Steps to reproduce

On OS X with the new docker beta running execute the command `rake spec` or `rake`
###### Expected outcome

According to the README the specs should run without a problem.
###### Actual outcome

Instead I get this error trace:

``` ruby
Users/nateh/.rvm/rubies/ruby-2.2.3/bin/ruby -I/Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib:/Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.4.1/lib /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
ifconfig: interface docker0 does not exist
/Users/nateh/.rvm/gems/ruby-2.2.3/gems/docker-api-1.25.0/lib/docker/connection.rb:42:in `rescue in request': 400 Bad Request: malformed Host header (Docker::Error::ClientError)
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/docker-api-1.25.0/lib/docker/connection.rb:38:in `request'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/docker-api-1.25.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/docker-api-1.25.0/lib/docker/container.rb:277:in `create'
    from /Users/nateh/code/open/ruby-kafka/spec/test_cluster.rb:209:in `create'
    from /Users/nateh/code/open/ruby-kafka/spec/test_cluster.rb:19:in `initialize'
    from /Users/nateh/code/open/ruby-kafka/spec/spec_helper.rb:63:in `new'
    from /Users/nateh/code/open/ruby-kafka/spec/spec_helper.rb:63:in `<top (required)>'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `require'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `block in requires='
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `each'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `requires='
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `each'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:21:in `configure'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:101:in `setup'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
    from /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
/Users/nateh/.rvm/rubies/ruby-2.2.3/bin/ruby -I/Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib:/Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.4.1/lib /Users/nateh/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by natesholland** [comment]
As an additional note: I'm running this version of docker on my mac: Version 1.12.0-rc2-beta17 (build: 9779)

**Comment by dasch** [comment]
It looks like it's due to [this line](https://github.com/zendesk/ruby-kafka/blob/master/spec/test_cluster.rb#L9) not working on OS X 10.11.

**Comment by dasch** [comment]
Have they changed the network name?

**Comment by natesholland** [comment]
It appears so, how would I check if the network name has changed?

**Comment by dasch** [comment]
Not really sure, I just got this stuff from a Docker wizard. I imagine a bit of Googling would be involved – I'm still on the old OS, so I can't reproduce.

**Comment by jturkel** [comment]
Do you have to set the `DOCKER_HOST` environment variable to the address of the xhyve virtual machine that Docker for Mac is using under the covers?

**Comment by dasch** [comment]
If you set `DOCKER_HOST` (and make Docker available over the network) things should just work.

**Comment by dasch** [comment]
But it would be better if things Just Worked regardless...
