### ISSUE TITLE
stack level too deep in Rails

### ISSUE THREAD

**Issue by state-phasive** [zendesk/ruby-kafka#241]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.3.0
* Version of Kafka: Latest
* Version of ruby-kafka: 0.3.10
* Version of Rails: 5.0.0

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

config/initializers/kafka.rb:
```ruby
require 'kafka'

$kafka_broker = Kafka.new(seed_brokers: ENV['KAFKA_HOSTS'].split(','), logger: Rails.logger, client_id: 'core')

$kafka_producer = $kafka_broker.async_producer(delivery_interval: 2)

at_exit { $kafka_producer.shutdown }
```

app/controllers/api/v1/my_controller.rb:
```ruby
$kafka_producer.produce('test message', topic: 'some_topic', key: 'topic_9')
```
Trying the following also produces the same issue:
```ruby
payload = { stuff: 'test' }
$kafka_producer.produce(payload.to_json, topic: 'some_topic', key: 'topic_9')
```

###### Expected outcome

Send message to message server.

###### Actual outcome

The following output to our error log:
```
"exception": "stack level too deep",
  "backtrace": [
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `initialize_dup'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `dup'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `each'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `map'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `as_json'",
    "/home/my_code/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `each'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `map'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `as_json'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:52:in `as_json'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `each'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `map'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `as_json'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:52:in `as_json'",
    "/home/my_code/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'",
# ..... keeps repeating
```

I've followed example in documentation, and seems like it's not working.

Thanks.

**Comment by state-phasive** [comment]
Sorry, found the issue.  The error is being thrown at the line where .produce is called, but the error is actually further down in code.  Close or delete this.
