### ISSUE TITLE
Connection Error Handling for Producer

### ISSUE THREAD

**Issue by The-Drewid** [zendesk/ruby-kafka#387]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.3.3
* Version of Kafka: 2.10-0.10.1.1
* Version of ruby-kafka: 0.3.17

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

Do not have a kafka server running.

kafka_server_connection  = Kafka.new(seed_brokers: ['localhost:5555'], client_id: 'ruby-kafka')
producer = $kafka_server_connection.async_producer
producer.produce(@message, topic: 'streaming_output')
producer.deliver_messages
producer.shutdown

# Please write an example that reproduces the problem you're describing.
When a connection to kafka isn't possible the producer does not throw any error.

###### Expected outcome

Connection Error would be thrown

###### Actual outcome

No Errors are thrown

**Comment by dasch** [comment]
Can you paste the logs that you're seeing? The async producer is supposed to be resilient to problems, and is specifically designed to insulate the host app from crashes even when Kafka is unavailable, so it's not surprising that you're not seeing any errors.

**Comment by The-Drewid** [comment]
I don't have any logs. My kafka server is not running. When I run my ruby code which produces and delivers a message, it runs successfully even though there's nothing to write to.

The following is my kafka object that I create:
    Kafka.new(seed_brokers: [ENV['KAFKA_END_POINT']], client_id: 'ruby-kafka')

The following is the code to produce and deliver a message to a topic:
    producer = $kafka_server_connection.async_producer
    producer.produce(message, topic: topic)
    producer.deliver_messages
    producer.shutdown

Thanks for taking time to help

**Comment by dasch** [comment]
Can you instantiate the Kafka client like this?

```ruby
kafka = Kafka.new(seed_brokers: [ENV['KAFKA_END_POINT']], client_id: 'ruby-kafka', logger: Logger.new(STDOUT))
```

Then run your code and paste the resulting output.

**Comment by The-Drewid** [comment]
I, [2017-08-11T16:22:17.960380 #12944]  INFO -- : New topics added to target list: streaming_output
I, [2017-08-11T16:22:17.960380 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:17.960380 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:17.978883 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:17.979383 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:17.989385 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:17.989385 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:17.989886 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
D, [2017-08-11T16:22:17.989886 #12944] DEBUG -- : Current leader for streaming_output/0 is node 1b34de8e9eaa:9092 (node_id=1001)
I, [2017-08-11T16:22:17.990386 #12944]  INFO -- : Sending 1 messages to 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:17.990386 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:20.256839 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:20.256839 #12944] ERROR -- : Could not connect to broker 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
W, [2017-08-11T16:22:20.257339 #12944]  WARN -- : Failed to send all messages; attempting retry 1 of 2 after 1s
I, [2017-08-11T16:22:21.257539 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:21.258039 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:21.269541 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:21.270542 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:21.280544 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:21.281044 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:21.281044 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
D, [2017-08-11T16:22:21.281544 #12944] DEBUG -- : Current leader for streaming_output/0 is node 1b34de8e9eaa:9092 (node_id=1001)
I, [2017-08-11T16:22:21.281544 #12944]  INFO -- : Sending 1 messages to 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:21.282044 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:23.534994 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:23.535494 #12944] ERROR -- : Could not connect to broker 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
W, [2017-08-11T16:22:23.535494 #12944]  WARN -- : Failed to send all messages; attempting retry 2 of 2 after 1s
I, [2017-08-11T16:22:24.536195 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:24.536695 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:24.548197 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:24.549197 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:24.559199 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:24.559699 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:24.560199 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
D, [2017-08-11T16:22:24.560699 #12944] DEBUG -- : Current leader for streaming_output/0 is node 1b34de8e9eaa:9092 (node_id=1001)
I, [2017-08-11T16:22:24.561200 #12944]  INFO -- : Sending 1 messages to 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:24.561200 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:26.813650 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:26.814150 #12944] ERROR -- : Could not connect to broker 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:26.814150 #12944] ERROR -- : Failed to send all messages; keeping remaining messages in buffer
I, [2017-08-11T16:22:26.814650 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:26.814650 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:26.826152 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:26.826653 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:26.837155 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:26.837655 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:26.837655 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
D, [2017-08-11T16:22:26.838155 #12944] DEBUG -- : Current leader for streaming_output/0 is node 1b34de8e9eaa:9092 (node_id=1001)
I, [2017-08-11T16:22:26.838655 #12944]  INFO -- : Sending 1 messages to 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:26.838655 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:29.091105 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:29.091605 #12944] ERROR -- : Could not connect to broker 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
W, [2017-08-11T16:22:29.091605 #12944]  WARN -- : Failed to send all messages; attempting retry 1 of 2 after 1s
I, [2017-08-11T16:22:30.092306 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:30.092806 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:30.104308 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:30.105308 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:30.115310 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:30.115810 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:30.115810 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
D, [2017-08-11T16:22:30.116810 #12944] DEBUG -- : Current leader for streaming_output/0 is node 1b34de8e9eaa:9092 (node_id=1001)
I, [2017-08-11T16:22:30.116810 #12944]  INFO -- : Sending 1 messages to 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:30.117311 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:32.369761 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:32.370261 #12944] ERROR -- : Could not connect to broker 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
W, [2017-08-11T16:22:32.370261 #12944]  WARN -- : Failed to send all messages; attempting retry 2 of 2 after 1s
I, [2017-08-11T16:22:33.370961 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:33.371461 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:33.382964 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:33.383964 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:33.393966 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:33.394466 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:33.394466 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
D, [2017-08-11T16:22:33.394966 #12944] DEBUG -- : Current leader for streaming_output/0 is node 1b34de8e9eaa:9092 (node_id=1001)
I, [2017-08-11T16:22:33.395466 #12944]  INFO -- : Sending 1 messages to 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:33.395466 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:35.647916 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:35.648417 #12944] ERROR -- : Could not connect to broker 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:35.648417 #12944] ERROR -- : Failed to send all messages; keeping remaining messages in buffer
I, [2017-08-11T16:22:35.648417 #12944]  INFO -- : Disconnecting broker 1001
D, [2017-08-11T16:22:35.648417 #12944] DEBUG -- : Closing socket to 1b34de8e9eaa:9092
I, [2017-08-11T16:22:35.649417 #12944]  INFO -- : New topics added to target list: streaming_output
I, [2017-08-11T16:22:35.649417 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:35.649917 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:35.660419 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:35.661419 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:35.671421 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:35.671921 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:35.671921 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
I, [2017-08-11T16:22:35.672421 #12944]  INFO -- : Joining group `my-group`
D, [2017-08-11T16:22:35.672921 #12944] DEBUG -- : Getting group coordinator for `my-group`
D, [2017-08-11T16:22:35.673422 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:37.925872 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:37.926372 #12944] ERROR -- : Failed to get group coordinator info from 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
I, [2017-08-11T16:22:37.926872 #12944]  INFO -- : Leaving group `my-group`
D, [2017-08-11T16:22:37.926872 #12944] DEBUG -- : Getting group coordinator for `my-group`
D, [2017-08-11T16:22:37.927372 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:40.180323 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:40.180323 #12944] ERROR -- : Failed to get group coordinator info from 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 

Kafka::Error: Failed to find group coordinator
./features/support/module_methods/kaf_connect.rb:14:in `listen_to_topic'
./features/step_definitions/component_level_steps.rb:54:in `/^the message is consumed from the topic$/'
./features/scenarios/component_level.feature:19:in `Then the message is consumed from the topic'
1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m22.263s

Process finished with exit code 1

**Comment by The-Drewid** [comment]
OK. Thank you for your help.
