### ISSUE TITLE
Failed to find group coordinator

### ISSUE THREAD

**Issue by The-Drewid** [zendesk/ruby-kafka#392]
Hi again,

This is not a bug, we are just unsure of what we're missing in our code or environment that is resulting in the following error:

```
I, [2017-08-11T16:22:35.649417 #12944]  INFO -- : New topics added to target list: streaming_output
I, [2017-08-11T16:22:35.649417 #12944]  INFO -- : Fetching cluster metadata from kafka://192.168.99.100:9092
D, [2017-08-11T16:22:35.649917 #12944] DEBUG -- : Opening connection to 192.168.99.100:9092 with client id ruby-kafka...
D, [2017-08-11T16:22:35.660419 #12944] DEBUG -- : Sending request 1 to 192.168.99.100:9092
D, [2017-08-11T16:22:35.661419 #12944] DEBUG -- : Waiting for response 1 from 192.168.99.100:9092
D, [2017-08-11T16:22:35.671421 #12944] DEBUG -- : Received response 1 from 192.168.99.100:9092
I, [2017-08-11T16:22:35.671921 #12944]  INFO -- : Discovered cluster metadata; nodes: 1b34de8e9eaa:9092 (node_id=1001)
D, [2017-08-11T16:22:35.671921 #12944] DEBUG -- : Closing socket to 192.168.99.100:9092
I, [2017-08-11T16:22:35.672421 #12944]  INFO -- : Joining group `my-group`
D, [2017-08-11T16:22:35.672921 #12944] DEBUG -- : Getting group coordinator for `my-group`
D, [2017-08-11T16:22:35.673422 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:37.925872 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:37.926372 #12944] ERROR -- : Failed to get group coordinator info from 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 
I, [2017-08-11T16:22:37.926872 #12944]  INFO -- : Leaving group `my-group`
D, [2017-08-11T16:22:37.926872 #12944] DEBUG -- : Getting group coordinator for `my-group`
D, [2017-08-11T16:22:37.927372 #12944] DEBUG -- : Opening connection to 1b34de8e9eaa:9092 with client id ruby-kafka...
E, [2017-08-11T16:22:40.180323 #12944] ERROR -- : Failed to connect to 1b34de8e9eaa:9092: getaddrinfo: No such host is known. 
E, [2017-08-11T16:22:40.180323 #12944] ERROR -- : Failed to get group coordinator info from 1b34de8e9eaa:9092 (node_id=1001): getaddrinfo: No such host is known. 

Kafka::Error: Failed to find group coordinator
./features/support/module_methods/kaf_connect.rb:14:in `listen_to_topic'
./features/step_definitions/component_level_steps.rb:54:in `/^the message is consumed from the topic$/'
./features/scenarios/component_level.feature:19:in `Then the message is consumed from the topic'
1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m22.263s

Process finished with exit code 1


Thanks again,

Drewid

**Comment by dasch** [comment]
The group coordinator is a Kafka broker that is elected to coordinate a specific consumer group. It seems that your broker advertises its own hostname as `1b34de8e9eaa`, which is not accessible from where you're running the client.
