### ISSUE TITLE
Consumer infinite OffsetOutOfRange loop

### ISSUE THREAD

**Issue by will89** [zendesk/ruby-kafka#420]
* Version of Ruby: 2.4.2
* Version of Kafka: 0.9.0.1
* Version of ruby-kafka: 0.4.0

In our production application, which had been running for about 10 days. We received the following log message repeatedly from ruby-kafka for about 3 hours.

`Invalid offset for topic/23, resetting to default offset`

Restarting our consumer process seemed to fix the issue. After investigating, it appears our replicas were out of sync. Is it possible this error case, https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L407, needs to do `@cluster.mark_as_stale!`?

**Comment by dasch** [comment]
Thanks for reporting this! I’m on vacation for the next two weeks, but I’ll take a look at this when I’m back.

**Comment by dasch** [comment]
Can you start by updating to the most recent version of the library?

**Comment by mensfeld** [comment]
@will89 @dasch we do the same: we recreate consumer after stopping the problematic one.

**Comment by will89** [comment]
Updated to 0.4.2.

Reproduced by doing the following:
Running with 3 brokers
3 brokers
And a topic with the following config
```
bin/kafka-topics.sh --zookeeper localhost:2181 --create --topic my_topic --partitions 3 --replication-factor 2
bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic my_topic --config retention.ms=60000
bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic my_topic --config segment.bytes=1_741_824
bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic my_topic --config segment.bytes=1741824
```

The next part is a bit unscientific but while data is being published and consumed, turn brokers on/off. You might need to keep repeating this process until the loop hangs, since sometimes it results in crashes.

I got the following several times, not sure if it's expected or not.
```
Kafka::OffsetCommitError: Kafka::NotCoordinatorForGroup
/Users/will/repos/ruby-kafka/lib/kafka/consumer_group.rb:87:in `rescue in commit_offsets'
/Users/will/repos/ruby-kafka/lib/kafka/consumer_group.rb:72:in `commit_offsets'
/Users/will/repos/ruby-kafka/lib/kafka/offset_manager.rb:67:in `commit_offsets'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:342:in `make_final_offsets_commit!'
```

```
Kafka::OffsetCommitError: No broker with id 1
/Users/will/repos/ruby-kafka/lib/kafka/consumer_group.rb:87:in `rescue in commit_offsets'
/Users/will/repos/ruby-kafka/lib/kafka/consumer_group.rb:72:in `commit_offsets'
/Users/will/repos/ruby-kafka/lib/kafka/offset_manager.rb:67:in `commit_offsets'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:342:in `make_final_offsets_commit!'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:336:in `ensure in consumer_loop'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:338:in `consumer_loop'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:246:in `each_batch'
```

```
Kafka::Error: Failed to find group coordinator
/Users/will/repos/ruby-kafka/lib/kafka/cluster.rb:110:in `get_group_coordinator'
/Users/will/repos/ruby-kafka/lib/kafka/consumer_group.rb:175:in `coordinator'
/Users/will/repos/ruby-kafka/lib/kafka/consumer_group.rb:116:in `block in join_group'
```

```
Errno::EPROTOTYPE: Protocol wrong type for socket
/Users/will/repos/ruby-kafka/lib/kafka/socket_with_timeout.rb:79:in `write'
/Users/will/repos/ruby-kafka/lib/kafka/socket_with_timeout.rb:79:in `write'
/Users/will/repos/ruby-kafka/lib/kafka/protocol/encoder.rb:23:in `write'
/Users/will/repos/ruby-kafka/lib/kafka/protocol/encoder.rb:95:in `write_bytes'
/Users/will/repos/ruby-kafka/lib/kafka/connection.rb:169:in `write_request'
/Users/will/repos/ruby-kafka/lib/kafka/connection.rb:99:in `block in send_request'
...
/Users/will/repos/ruby-kafka/lib/kafka/instrumenter.rb:19:in `instrument'
/Users/will/repos/ruby-kafka/lib/kafka/connection.rb:93:in `send_request'
/Users/will/repos/ruby-kafka/lib/kafka/broker.rb:40:in `fetch_messages'
/Users/will/repos/ruby-kafka/lib/kafka/fetch_operation.rb:68:in `block in execute'
/Users/will/repos/ruby-kafka/lib/kafka/fetch_operation.rb:59:in `each'
/Users/will/repos/ruby-kafka/lib/kafka/fetch_operation.rb:59:in `flat_map'
/Users/will/repos/ruby-kafka/lib/kafka/fetch_operation.rb:59:in `execute'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:403:in `fetch_batches'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:247:in `block in each_batch'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:319:in `consumer_loop'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:246:in `each_batch'
```

This is what the loop looks like when it hangs:
```
Sending request 793037 to localhost:9096
Waiting for response 793037 from localhost:9096
Received response 793037 from localhost:9096
Invalid offset for my_topic/2, resetting to default offset
Fetching batch from my_topic/2 starting at offset 11599
Fetching batch from my_topic/1 starting at offset 11738
Fetching batch from my_topic/0 starting at offset 11477
Sending request 793038 to localhost:9096
Waiting for response 793038 from localhost:9096
Received response 793038 from localhost:9096
Invalid offset for my_topic/2, resetting to default offset
Fetching batch from my_topic/2 starting at offset 11599
Fetching batch from my_topic/1 starting at offset 11738
Fetching batch from my_topic/0 starting at offset 11477
...
```

While this loop was going on
```
bin/kafka-consumer-groups.sh --describe --new-consumer --bootstrap-server localhost:9092 --group my_group
GROUP, TOPIC, PARTITION, CURRENT OFFSET, LOG END OFFSET, LAG, OWNER
my_group, my_topic, 0, unknown, 14452, unknown, ruby-kafka_/127.0.0.1
my_group, my_topic, 1, unknown, 15113, unknown, ruby-kafka_/127.0.0.1
my_group, my_topic, 2, unknown, 14880, unknown, ruby-kafka_/127.0.0.1
```

```
bin/kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list localhost:9092,localhost:9096 --topic my_topic --time -2 --offsets 1
my_topic:2:14880
my_topic:1:15113
my_topic:0:14452
```

It appears the ruby-kafka consumer is getting the incorrect offsets. After digging around, it appeared the consumer wasn't actually making an API call to get the latest metadata from the cluster and I think this is the reason why, https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/offset_manager.rb#L108.

**Comment by dasch** [comment]
In the case of a offset error, `seek_to_default` should fix the error...

**Comment by dasch** [comment]
I am currently on vacation, but will look at this once I’m back.

**Comment by dasch** [comment]
@will89 can you try to see if this fixes the issue? https://github.com/zendesk/ruby-kafka/pull/431

**Comment by will89** [comment]
Will do.

**Comment by will89** [comment]
I got the following stack trace
```
KeyError: key not found: 0
/Users/will/repos/ruby-kafka/lib/kafka/offset_manager.rb:116:in `fetch'
/Users/will/repos/ruby-kafka/lib/kafka/offset_manager.rb:116:in `resolve_offset'
/Users/will/repos/ruby-kafka/lib/kafka/offset_manager.rb:58:in `next_offset_for'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:391:in `block (2 levels) in fetch_batches'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:390:in `each'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:390:in `block in fetch_batches'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:389:in `each'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:389:in `fetch_batches'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:247:in `block in each_batch'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:319:in `consumer_loop'
/Users/will/repos/ruby-kafka/lib/kafka/consumer.rb:246:in `each_batch'
```

**Comment by dasch** [comment]
@will89 I've force pushed the branch, can you try at the latest revision?

**Comment by will89** [comment]
Seems to be working now. 👍

**Comment by dasch** [comment]
Awesome, thanks for testing!
