### ISSUE TITLE
Always getting Kafka::LeaderNotAvailable

### ISSUE THREAD

**Issue by Barlog951** [zendesk/ruby-kafka#427]
* Version of Ruby: 2.3.1
* Version of Kafka: 0.11.0.1 
* Version of ruby-kafka: 0.4.2
###### Steps to reproduce

```ruby
require "kafka"
kafka = Kafka.new(seed_brokers: ["localhost:9092"], logger: Logger.new(STDOUT))
kafka.deliver_message("Hello, World!", topic: "test")
```

###### Error message

```
I, [2017-10-09T13:24:49.354163 #75383]  INFO -- : New topics added to target list: test
I, [2017-10-09T13:24:49.355322 #75383]  INFO -- : Fetching cluster metadata from kafka://localhost:9092
D, [2017-10-09T13:24:49.355473 #75383] DEBUG -- : Opening connection to localhost:9092 with client id ruby-kafka...
D, [2017-10-09T13:24:49.368196 #75383] DEBUG -- : Sending request 1 to localhost:9092
D, [2017-10-09T13:24:49.368374 #75383] DEBUG -- : Waiting for response 1 from localhost:9092
D, [2017-10-09T13:24:49.442087 #75383] DEBUG -- : Received response 1 from localhost:9092
I, [2017-10-09T13:24:49.442212 #75383]  INFO -- : Discovered cluster metadata; nodes: 
D, [2017-10-09T13:24:49.442241 #75383] DEBUG -- : Closing socket to localhost:9092
Kafka::LeaderNotAvailable: Kafka::LeaderNotAvailable
	from /Users/Dodko/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.4.2/lib/kafka/protocol.rb:96:in `handle_error'
	from /Users/Dodko/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.4.2/lib/kafka/protocol/metadata_response.rb:138:in `partitions_for'
	from /Users/Dodko/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.4.2/lib/kafka/cluster.rb:116:in `partitions_for'
	from /Users/Dodko/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.4.2/lib/kafka/client.rb:112:in `deliver_message'
	from (irb):5
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by dasch** [comment]
Does the topic exist? After a topic is created, it takes a while for a leader to be elected for all its partitions. The simple producer API doesn't support retries, so this (ephemeral) error is to be expected.

**Comment by dasch** [comment]
Closing due to a lack of activity. The problem seems to be due to the topic either not existing or not being configured correctly.

**Comment by DragWeb** [comment]
@dasch How did you resolve this problem?

**Comment by mensfeld** [comment]
@DragWeb let me answer (hope @dasch don't mind): he didn't.

The issue was closed because you didn't provide any additional info, you didn't answer questions, you didn't try newer ruby-kafka versions and it seems to me, that he answered that issue report correctly.
