### ISSUE TITLE
Connection Error / Failed to fetch metadata / Errno::ETIMEDOUT: Connection timed out

### ISSUE THREAD

**Issue by edsiper** [zendesk/ruby-kafka#498]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.4
* Version of Kafka: v0.10.0.0
* Version of ruby-kafka: v0.5.1

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

We are facing an issue when delivering a message we get a timeout from Kafka Side, this is the output error we are getting from our script that uses ruby-kafka:

```
I, [2017-12-06T01:05:07.922443 #6436]  INFO -- : New topics added to target list: fluentd
I, [2017-12-06T01:05:07.922520 #6436]  INFO -- : Fetching cluster metadata from kafka://kafka.example.com:9095
D, [2017-12-06T01:05:07.922582 #6436] DEBUG -- : Opening connection to kafka.example.com:9095 with client id ruby-kafka...
D, [2017-12-06T01:05:07.939300 #6436] DEBUG -- : Sending sasl_handshake API request 1 to kafka.example.com:9095
D, [2017-12-06T01:05:07.939473 #6436] DEBUG -- : Waiting for response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:07.941101 #6436] DEBUG -- : Received response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:07.957806 #6436] DEBUG -- : GSSAPI: Initializing context with kafka.example.com:9095, principal kafka@kafka.example.com
D, [2017-12-06T01:05:07.968115 #6436] DEBUG -- : Sending topic_metadata API request 2 to kafka.example.com:9095
D, [2017-12-06T01:05:07.968240 #6436] DEBUG -- : Waiting for response 2 from kafka.example.com:9095
E, [2017-12-06T01:05:17.978989 #6436] ERROR -- : Timed out while waiting for response 2
D, [2017-12-06T01:05:17.979269 #6436] DEBUG -- : Closing socket to kafka.example.com:9095
D, [2017-12-06T01:05:17.979526 #6436] DEBUG -- : Closing socket to kafka.example.com:9095
E, [2017-12-06T01:05:17.979749 #6436] ERROR -- : Failed to fetch metadata from kafka://kafka.example.com:9095: Connection error Errno::ETIMEDOUT: Connection timed out
D, [2017-12-06T01:05:17.979892 #6436] DEBUG -- : Opening connection to kafka.example.com:9095 with client id ruby-kafka...
D, [2017-12-06T01:05:18.002404 #6436] DEBUG -- : Sending sasl_handshake API request 1 to kafka.example.com:9095
D, [2017-12-06T01:05:18.002545 #6436] DEBUG -- : Waiting for response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:18.005036 #6436] DEBUG -- : Received response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:18.005136 #6436] DEBUG -- : GSSAPI: Initializing context with kafka.example.com:9095, principal kafka@kafka.example.com
D, [2017-12-06T01:05:18.013008 #6436] DEBUG -- : Closing socket to kafka.example.com:9095
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:286:in `fetch_cluster_info': Could not connect to any of the seed brokers: (Kafka::ConnectionError)
- kafka://kafka.example.com:9095: Connection error Errno::ETIMEDOUT: Connection timed out
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:246:in `cluster_info'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:82:in `refresh_metadata!'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:48:in `add_target_topics'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/cluster.rb:140:in `partitions_for'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/ruby-kafka-0.5.1/lib/kafka/client.rb:125:in `deliver_message'
	from test.rb:15:in `<main>'
```

the script to replicate the problem is here:

```ruby
require "kafka"
require "logger"

k=Kafka.new(
  logger: Logger.new(STDOUT),
  seed_brokers: ["kafka.example.com:9095"],
  #sasl_gssapi_principal: "kafkaclient/kafka.example.com@EXAMPLE.com",
  sasl_gssapi_principal: "kafka@kafka.example.com",
  sasl_gssapi_keytab: "/etc/security/keytabs/kafkaclient.keytab",
  ssl_ca_cert: File.read("/home/vagrant/ca-cert"))

k.deliver_message('abc', topic: 'fluentd')
```

the problem can be easily replicated using the following vagrant image that setup Kafka+SSL+Kerberos:

https://github.com/confluentinc/securing-kafka-blog

###### Expected outcome

Expect to publish messages

###### Actual outcome

Disconnect error

**Comment by dasch** [comment]
@edsiper unfortunately, you'll need to upgrade your Kafka cluster to v0.10.1 or higher – see [the compatibility table](https://github.com/zendesk/ruby-kafka#compatibility).

**Comment by fyery-chen** [comment]
@edsiper hello, I want to know whether you have solved this problem because I met this as well.
