### ISSUE TITLE
Send exception occurred: data error

### ISSUE THREAD

**Issue by felixzh2015** [zendesk/ruby-kafka#539]
If this is a bug report, please fill out the following:

* Version of Ruby:
ruby-2.4.0
* Version of Kafka:
0.10.2
* Version of ruby-kafka:
0.4.0
* Version of flunetd:
0.14.20
* Version of flunet-plugin-kafka:
0.6.0
* Version of OS:
centos in docker 

Hello, when I use fluentd(https://github.com/fluent/fluentd)'s  fluent-plugin-kafka(https://github.com/fluent/fluent-plugin-kafka) , I produce message to kafka and get warnings, as follows:

```
2018-02-06 09:44:21 +0000 [warn]: #0 Send exception occurred: data error
2018-02-06 09:44:21 +0000 [warn]: #0 Exception Backtrace : /usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/gzip_codec.rb:17:in `close'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/gzip_codec.rb:17:in `compress'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/compressor.rb:50:in `block in compress_data'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/instrumenter.rb:21:in `instrument'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/compressor.rb:49:in `compress_data'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/compressor.rb:34:in `compress'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/produce_operation.rb:89:in `block (2 levels) in send_buffered_messages'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/message_buffer.rb:44:in `block (2 levels) in each'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/message_buffer.rb:43:in `each'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/message_buffer.rb:43:in `block in each'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/message_buffer.rb:42:in `each'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/message_buffer.rb:42:in `each'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/produce_operation.rb:87:in `block in send_buffered_messages'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/produce_operation.rb:81:in `each'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/produce_operation.rb:81:in `send_buffered_messages'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/produce_operation.rb:47:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/instrumenter.rb:21:in `instrument'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/produce_operation.rb:41:in `execute'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/producer.rb:301:in `block in deliver_messages_with_retries'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/producer.rb:293:in `loop'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/producer.rb:293:in `deliver_messages_with_retries'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/producer.rb:243:in `block in deliver_messages'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/instrumenter.rb:21:in `instrument'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/ruby-kafka-0.4.0/lib/kafka/producer.rb:236:in `deliver_messages'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/fluent-plugin-kafka-0.6.0/lib/fluent/plugin/out_kafka_buffered.rb:246:in `deliver_messages'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/fluent-plugin-kafka-0.6.0/lib/fluent/plugin/out_kafka_buffered.rb:309:in `write'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/fluentd-0.14.20/lib/fluent/compat/output.rb:131:in `write'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:1043:in `try_flush'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:1268:in `flush_thread_run'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/fluentd-0.14.20/lib/fluent/plugin/output.rb:420:in `block (2 levels) in start'
/usr/local/rvm/gems/ruby-2.4.0@fluentd/gems/fluentd-0.14.20/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
Any suggestions?
out_kafka_buffered's configure:
<match **>
  @type kafka_buffered
  brokers       192.168.1.1:9092
  buffer_type   file
  buffer_path  /var/log/fluent/buffer-01/*.buffer

  flush_interval 1s
  buffer_chunk_limit 4m
  buffer_queue_limit 43200

  retry_wait          1s
  max_retry_wait      60s
  disable_retry_limit true

  # ruby-kafka producer options
  max_send_retries    1
  required_acks       1
  compression_codec   gzip
  output_data_type json
  output_include_time true
  num_threads   1
  #kafka_agg_max_bytes 1048576
</match>
```

**Comment by dasch** [comment]
1) This probably belongs in the fluentd error tracker.
2) Can you see what the original exception class was?
3) Start by upgrading to ruby-kafka v0.4.4.

**Comment by jl2005** [comment]
I have same error

```
2018-05-07 03:24:44 +0800 [warn]: failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-07 03:24:45 +0800 chunk="56b8e81424d18ec86e8a0c384c3c098b" error_class=Zlib::DataError error="data error"
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/gzip_codec.rb:17:in `close'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/gzip_codec.rb:17:in `compress'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:54:in `block in compress_data'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:53:in `compress_data'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:37:in `compress'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:89:in `block (2 levels) in send_buffered_messages'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:44:in `block (2 levels) in each'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:43:in `each'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:43:in `block in each'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:42:in `each'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:42:in `each'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:87:in `block in send_buffered_messages'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:81:in `each'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:81:in `send_buffered_messages'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:47:in `block in execute'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:41:in `execute'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:298:in `block in deliver_messages_with_retries'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:286:in `loop'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:286:in `deliver_messages_with_retries'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:236:in `block in deliver_messages'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:229:in `deliver_messages'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:277:in `deliver_messages'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:340:in `write'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/compat/output.rb:131:in `write'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-05-07 03:24:44 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by dasch** [comment]
Is there a way to get the ruby-kafka exception rather than the fluentd exception? Also, can you turn on debug logging for ruby-kafka?
