### ISSUE TITLE
Always getting Kafka::LeaderNotAvailable

### ISSUE THREAD

**Issue by mrkamel** [zendesk/ruby-kafka#55]
```ruby
kafka = Kafka.new(:seed_brokers => ["127.0.0.1:9093", "127.0.0.1:9094", "127.0.0.1:9095"], :client_id => "my-app", :logger => Logger.new(STDOUT))
producer = kafka.get_producer
producer.produce("value", :topic => "my-test")
I, [2016-02-06T20:27:55.716158 #12271]  INFO -- : Trying to initialize broker pool from node 127.0.0.1:9093
I, [2016-02-06T20:27:55.716365 #12271]  INFO -- : Opening connection to 127.0.0.1:9093 with client id my-app...
D, [2016-02-06T20:27:55.716890 #12271] DEBUG -- : Sending request 1 to 127.0.0.1:9093
D, [2016-02-06T20:27:55.717281 #12271] DEBUG -- : Waiting for response 1 from 127.0.0.1:9093
D, [2016-02-06T20:27:55.736754 #12271] DEBUG -- : Received response 1 from 127.0.0.1:9093
D, [2016-02-06T20:27:55.737007 #12271] DEBUG -- : Closing socket to 127.0.0.1:9093
Kafka::LeaderNotAvailable: Kafka::LeaderNotAvailable
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/protocol.rb:32:in `handle_error'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker.rb:37:in `block (2 levels) in fetch_metadata'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker.rb:35:in `each'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker.rb:35:in `block in fetch_metadata'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker.rb:32:in `each'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker.rb:32:in `fetch_metadata'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker_pool.rb:95:in `block in fetch_cluster_info'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker_pool.rb:81:in `each'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker_pool.rb:81:in `fetch_cluster_info'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker_pool.rb:69:in `cluster_info'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/broker_pool.rb:44:in `partitions_for'
	from /var/lib/gems/2.1.0/gems/ruby-kafka-0.1.2/lib/kafka/producer.rb:158:in `produce'
	from (irb):36
	from /usr/bin/irb:11:in `<main>'
```

Using kafka_2.11-0.9.0.0. It's working with poseidon, as well as a python kafka client.

**Comment by mrkamel** [comment]
Found the issue. For one of my created test-topics kafka indeed returned partition_error_code 5 (Leader not available), not sure why, yet. However the partitions for the topic (my-test) i tried writing to (see above) were fine. ruby-kafka nevertheless raises the exception, as it checks all topics/partitions and if one is not ok, it raises (See Kafka::Broker#fetch_metadata). E.g. the python kafka client seems to only raise lazily, i.e. not after the initial metadata fetch directly, but when you try to write to a faulty topic/partition.

**Comment by dasch** [comment]
That's definitely a bug - I'll issue a fix ASAP. Thanks for reporting this!

**Comment by dasch** [comment]
@mrkamel I have fixed this issue in v0.1.3. Please report back if you're still seeing it. Thanks!

**Comment by mrkamel** [comment]
Seems to work perfectly, thx!

**Comment by dasch** [comment]
Awesome!
