### ISSUE TITLE
Crash with 0.6.1

### ISSUE THREAD

**Issue by dorner** [zendesk/ruby-kafka#580]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.4.2
* Version of Kafka: 0.10.0
* Version of ruby-kafka: 0.6.1

I'm running Phobos and it auto-upgraded to 0.6.1 It looks like the frozen string literal that was added is causing issues:

```
ERROR -- Phobos : <Hash> {:message=>"Listener crashed, waiting 57.74s (can't modify frozen String)", :listener_id=>"3646d0", :retry_count=>90, :waiting_time=>57.74, :exception_class=>"RuntimeError", :exception_message=>"can't modify frozen String", :backtrace=>[
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/ssl_socket_with_timeout.rb:101:in `read'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/protocol/decoder.rb:106:in `read'",
 "/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/protocol/decoder.rb:50:in `int32'",
 "/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/protocol/decoder.rb:90:in `bytes'",
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/connection.rb:182:in `read_response'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/connection.rb:201:in `block in wait_for_response'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/connection.rb:200:in `loop'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/connection.rb:200:in `wait_for_response'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/connection.rb:106:in `block in send_request'",
 "/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'",
 "/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/instrumenter.rb:21:in `instrument'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/connection.rb:96:in `send_request'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/broker.rb:158:in `send_request'",
 "/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/broker.rb:44:in `fetch_metadata'",
 "/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/cluster.rb:370:in `block in fetch_cluster_info'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/cluster.rb:365:in `each'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/cluster.rb:365:in `fetch_cluster_info'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/cluster.rb:351:in `cluster_info'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/cluster.rb:95:in `refresh_metadata!'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/cluster.rb:50:in `add_target_topics'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/consumer_group.rb:27:in `subscribe'", 
"/usr/local/bundle/gems/ruby-kafka-0.6.1/lib/kafka/consumer.rb:98:in `subscribe'", 
"/usr/local/bundle/gems/phobos-1.7.2/lib/phobos/listener.rb:55:in `block in start'",
...
```

**Comment by dasch** [comment]
Thanks for the report, #584 should fix the problem.
