### ISSUE TITLE
SSL Error when connecting to client cert authenticated kafka

### ISSUE THREAD

**Issue by redbeard0x0a** [zendesk/ruby-kafka#632]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.5.1 (should be any)
* Version of Kafka: `ii confluent-platform-oss-2.11            4.1.2-1`
* Version of ruby-kafka: 0.6.7 (and master)

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

The server needs to be configured to trust the organization's Root CA for client certificate authentication. The client cert needs to be generated by the Intermediate CA, the int_ca isn't part of the truststore on the server, only the root_ca.

```ruby
client_key = IO.read('/path/to/client_key.pem')
client_cert = IO.read('/path/to/client_cert.pem')
ca_cert = IO.read('/path/to/ca.pem')
kafka = Kafka.new(ssl_client_cert: client_cert, ssl_client_cert_key: client_key, ssl_ca_cert: ca_cert)

kafka.topics
```

###### Expected outcome

I expect the topics to be listed. (This applies to any kafka operation)

###### Actual outcome

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=unknown state: unexpected message)

```
I, [2018-08-20T14:18:45.070086 #95763]  INFO -- : Fetching cluster metadata from kafka://broker0.kafka-sbx.venuenext.net:9092
D, [2018-08-20T14:18:45.070688 #95763] DEBUG -- : Opening connection to broker0.kafka-sbx.venuenext.net:9092 with client id portico-rb-eventa...
D, [2018-08-20T14:18:45.321117 #95763] DEBUG -- : Closing socket to broker0.kafka-sbx.venuenext.net:9092
Traceback (most recent call last):
       16: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/client.rb:587:in `topics'
       15: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/cluster.rb:347:in `list_topics'
       14: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/cluster.rb:417:in `random_broker'
       13: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/cluster.rb:367:in `cluster_info'
       12: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/cluster.rb:387:in `fetch_cluster_info'
       11: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/cluster.rb:387:in `each'
       10: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/cluster.rb:392:in `block in fetch_cluster_info'
        9: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/broker.rb:44:in `fetch_metadata'
        8: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/broker.rb:170:in `send_request'
        7: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/connection.rb:96:in `send_request'
        6: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/instrumenter.rb:23:in `instrument'
        5: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/connection.rb:97:in `block in send_request'
        4: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/connection.rb:124:in `open'
        3: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/connection.rb:124:in `new'
        2: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/ssl_socket_with_timeout.rb:68:in `initialize'
        1: from /Users/redbeard/dev/venuenext/ruby-kafka/lib/kafka/ssl_socket_with_timeout.rb:68:in `connect_nonblock'
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=unknown state: unexpected message)
```

---

I started working on a fix to the issue. The SSL Context needs to have an array of certificates provided to the `extra_chain_cert` property so the rest of the certificate chain can be sent to the server.

Here is my branch that I started working on the fix with: https://github.com/venuenext/ruby-kafka/tree/client_certs_intermediate_ca

I'll start a PR when I get some tests figured out.

**Comment by dasch** [comment]
:+1: thanks!
