### ISSUE TITLE
Client#topics never refreshes metedata

### ISSUE THREAD

**Issue by ttamimi** [zendesk/ruby-kafka#642]
* Version of Ruby: 2.3.3
* Version of Kafka: 0.11
* Version of ruby-kafka: 0.7.0

###### Steps to reproduce

1. Launch a new set of Kafka brokers
2. Migrate all topics to the new brokers
3. Kill the old brokers

###### Expected outcome

We are running a homegrown consumer lag monitoring tool. It repeatedly queries Kafka to fetch a list of all topics and their producer offsets. It also subscribes (in another thread) to `_consumer offsets`. When migrating to a new set of brokers, it is normal to see several errors (e.g. leader not found, unknown topic, connection error, etc.) The tool catches all errors and effectively just tries again on the next reporting cycle (every 60 seconds). We expect everything to eventually stabilise and no errors to be thrown as the cluster metadata gets refreshed.

###### Actual outcome

The following error repeats indefinitely:

```
E, [2018-09-10T15:53:18] ERROR -- : Timed out while trying to connect to xxxx:9092: Connection timed out
E, [2018-09-10T15:53:18] ERROR -- : Error in reporter main loop: Kafka::ConnectionError - Connection timed out

.../ruby-kafka-0.7.0/lib/kafka/connection.rb:138:in `rescue in open'
.../ruby-kafka-0.7.0/lib/kafka/connection.rb:121:in `open'
.../ruby-kafka-0.7.0/lib/kafka/connection.rb:97:in `block in send_request'
.../ruby-kafka-0.7.0/lib/kafka/instrumenter.rb:23:in `instrument'
.../ruby-kafka-0.7.0/lib/kafka/connection.rb:96:in `send_request'
.../ruby-kafka-0.7.0/lib/kafka/broker.rb:170:in `send_request'
.../ruby-kafka-0.7.0/lib/kafka/broker.rb:44:in `fetch_metadata'
.../ruby-kafka-0.7.0/lib/kafka/cluster.rb:347:in `list_topics'
.../ruby-kafka-0.7.0/lib/kafka/client.rb:587:in `topics'
```

**Comment by ttamimi** [comment]
It seems to me the issue is:
1. `Cluster#list_topics` picks a `random_broker` to fetch the latest cluster metadata
https://github.com/zendesk/ruby-kafka/blob/v0.7.0/lib/kafka/cluster.rb#L347
1. `Cluster#random_broker` relies on potentially stale metadata but never calls `refresh_metadata_if_necessary!`
https://github.com/zendesk/ruby-kafka/blob/v0.7.0/lib/kafka/cluster.rb#L417
1.  `Client#topics` never attempts to catch any errors and call `Cluster#mark_as_stale!`
https://github.com/zendesk/ruby-kafka/blob/v0.7.0/lib/kafka/client.rb#L587

**Comment by ttamimi** [comment]
This fixed the problem in my tests
https://github.com/zendesk/ruby-kafka/pull/643/files
