### ISSUE TITLE
Fail to resume operations after connection error.

### ISSUE THREAD

**Issue by l0x-c0d3z** [zendesk/ruby-kafka#653]
* Version of Ruby: 2.3.3
* Version of Kafka: 2.11.1-1.1.0
* Version of ruby-kafka: 0.5.5

Hi. I have a simple script that will basically read from a several topics on a (local) **source** broker, and copy those messages to a (remote) **target** broker.

The relevant code looks like this.

```ruby

        def run 
                sleep(@backoff)
                mappings = {}
                @backoff = @backoff * 2 + 1
                src = Kafka.new(@cfg['source']['broker'])
                tgt = Kafka.new(@cfg['target']['broker'])
                consumer = src.consumer(group_id: @cfg['source']['client_id'])
                producer = tgt.producer()

                @cfg['mappings'].each_pair do |from, to|
                        consumer.subscribe(from)
                        mappings[from] = to
                end

                n = 0
                consumer.each_batch do |batch|
                        begin   
                                batch.messages.each do |msg|
                                        n += 1
                                        producer.produce(msg.value, key: msg.key, topic: mappings[msg.topic])
                                        if n >= 100
                                                producer.deliver_messages
                                                consumer.mark_message_as_processed(msg)
                                                $logger.info "Send #{n} messages"
                                                n = 0
                                        end
                                end
                                if n > 0
                                        producer.deliver_messages
                                        $logger.info "Send #{n} messages"
                                end
                        rescue Exception => e
                                $logger.debug(e.message)
                                raise e
                        end
                end
        end
```

Due to connectivity issues, the target broker is sometimes unreachable, and the code raises `Could not connect to any of the seed brokers: - kafka://x.x.x.x:9092: Connection timed out`. This is normal and expected. However, when I call the function again, the code hangs on `consumer.each_batch`, and never returns a single message, until I kill and restart the entire process.

Not sure if it's relevant, but there is threading involved. I let the thread die, and restart it.

I'm unsure weather I'm doing something wrong, or if the library tries to re-use some state and therefore fails. Any help on this issue would be appreciated.

**Comment by nguyenquangminh0711** [comment]
Hi @l0x-c0d3z, when the consumers don't return anything, are there any suspicious logs? It would be helpful if you can provide the logs when this situation happens, and even more if the logs is at Debug level. One more thing, how did you handle the exception? You kill the thread that has your consumer and producer, then create a thread and re-run in it?

**Comment by l0x-c0d3z** [comment]
The exception is not caught, so the thread just dies. The main thread detects that and restarts it.

I just checked, but the interesting log part is now out of my screen buffer. I tried simulating the behavior by stopping the target kafka for a few seconds, but it does restart properly. I've added a debug Logger to the Kafka instances, and I'll post the logs as soon as it fails again.

Basically, I had the call stack from the `connection failed`, followed by the message saying the thread had been restarted, and then nothing until I killed it.

**Comment by nguyenquangminh0711** [comment]
Wait a sec. I have just realize that you are using ruby-kafka 0.5.5 right? From the version 0.6.x stable, ruby-kafka introduces a whole new mechanism of message fetching. What do you think about upgrading to newest stable version and retry again on prod to see whether this issue still exist? In addition, Kafka 0.11.1 and 1.1.0 are supported better (with fancy features) in newer ruby-kafka versions.

**Comment by l0x-c0d3z** [comment]
I'll give it a try and see if it works better.

**Comment by nguyenquangminh0711** [comment]
Hi @l0x-c0d3z, I haven't heard from you for a while. Does the newer version of ruby-kafka work for you?

**Comment by l0x-c0d3z** [comment]
It took longer than before, but I did have a worker crash a few days ago. Here's the debug log.

```
I, [2018-10-02T08:57:05.599527 #18366]  INFO -- : Send 100 messages
D, [2018-10-02T08:57:05.604211 #18366] DEBUG -- : Current leader for my.topic/0 is node 99.99.99.99:9092 (node_id=0)
I, [2018-10-02T08:57:05.604436 #18366]  INFO -- : Sending 100 messages to 99.99.99.99:9092 (node_id=0)
D, [2018-10-02T08:57:05.604546 #18366] DEBUG -- : Sending produce API request 9036 to 99.99.99.99:9092
D, [2018-10-02T08:57:05.630403 #18366] DEBUG -- : Waiting for response 9036 from 99.99.99.99:9092
D, [2018-10-02T08:57:06.026155 #18366] DEBUG -- : Received response 9036 from 99.99.99.99:9092
D, [2018-10-02T08:57:06.026608 #18366] DEBUG -- : Successfully appended 100 messages to my.topic/0 on 99.99.99.99:9092 (node_id=0)
D, [2018-10-02T08:57:06.026722 #18366] DEBUG -- : Marking my.local.topic/0:32992948 as processed
I, [2018-10-02T08:57:06.026762 #18366]  INFO -- : Send 100 messages
D, [2018-10-02T08:57:06.031436 #18366] DEBUG -- : Current leader for my.topic/0 is node 99.99.99.99:9092 (node_id=0)
I, [2018-10-02T08:57:06.031673 #18366]  INFO -- : Sending 100 messages to 99.99.99.99:9092 (node_id=0)
D, [2018-10-02T08:57:06.031780 #18366] DEBUG -- : Sending produce API request 9037 to 99.99.99.99:9092
W, [2018-10-02T08:57:06.057798 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
D, [2018-10-02T08:57:06.059035 #18366] DEBUG -- : Waiting for response 9037 from 99.99.99.99:9092
D, [2018-10-02T08:57:06.486424 #18366] DEBUG -- : Received response 9037 from 99.99.99.99:9092
D, [2018-10-02T08:57:06.486898 #18366] DEBUG -- : Successfully appended 100 messages to my.topic/0 on 99.99.99.99:9092 (node_id=0)
D, [2018-10-02T08:57:06.487009 #18366] DEBUG -- : Marking my.local.topic/0:32993048 as processed
I, [2018-10-02T08:57:06.487054 #18366]  INFO -- : Send 100 messages
D, [2018-10-02T08:57:06.491648 #18366] DEBUG -- : Current leader for my.topic/0 is node 99.99.99.99:9092 (node_id=0)
I, [2018-10-02T08:57:06.491873 #18366]  INFO -- : Sending 100 messages to 99.99.99.99:9092 (node_id=0)
D, [2018-10-02T08:57:06.491981 #18366] DEBUG -- : Sending produce API request 9038 to 99.99.99.99:9092
D, [2018-10-02T08:57:06.519985 #18366] DEBUG -- : Waiting for response 9038 from 99.99.99.99:9092
W, [2018-10-02T08:57:07.058102 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:08.058358 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:09.058640 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:10.058954 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:11.059205 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:12.059477 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:13.059733 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:14.059964 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:15.060255 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:16.060520 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
E, [2018-10-02T08:57:16.530021 #18366] ERROR -- : Timed out while waiting for response 9038
D, [2018-10-02T08:57:16.530372 #18366] DEBUG -- : Closing socket to 99.99.99.99:9092
D, [2018-10-02T08:57:16.530733 #18366] DEBUG -- : Closing socket to 99.99.99.99:9092
E, [2018-10-02T08:57:16.530881 #18366] ERROR -- : Could not connect to broker 99.99.99.99:9092 (node_id=0): Connection error Errno::ETIMEDOUT: Connection timed out
W, [2018-10-02T08:57:16.530943 #18366]  WARN -- : Failed to send all messages; attempting retry 1 of 2 after 1s
W, [2018-10-02T08:57:17.060779 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
I, [2018-10-02T08:57:17.531076 #18366]  INFO -- : Fetching cluster metadata from kafka://99.99.99.99:9092
D, [2018-10-02T08:57:17.531276 #18366] DEBUG -- : Opening connection to 99.99.99.99:9092 with client id ruby-kafka...
W, [2018-10-02T08:57:18.061049 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:19.061344 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:20.061589 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:21.061870 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:22.062152 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:23.062406 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:24.062696 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:25.062989 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:26.063260 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
W, [2018-10-02T08:57:27.063542 #18366]  WARN -- : Reached max fetcher queue size (100), sleeping 1s
E, [2018-10-02T08:57:27.536340 #18366] ERROR -- : Timed out while trying to connect to 99.99.99.99:9092: Connection timed out
D, [2018-10-02T08:57:27.536550 #18366] DEBUG -- : Closing socket to 99.99.99.99:9092
E, [2018-10-02T08:57:27.536980 #18366] ERROR -- : Failed to fetch metadata from kafka://99.99.99.99:9092: Connection timed out
D, [2018-10-02T08:57:27.538135 #18366] DEBUG -- : Could not connect to any of the seed brokers:
- kafka://99.99.99.99:9092: Connection timed out
E, [2018-10-02T08:57:27.538580 #18366] ERROR -- : Exception raised when processing my.local.topic/0 in offset range 32991083..32993293 -- Kafka::DeliveryFailed: Could not connect to any of the seed brokers:
- kafka://99.99.99.99:9092: Connection timed out
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/producer.rb:378:in `rescue in block in deliver_messages_with_retries'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/producer.rb:375:in `block in deliver_messages_with_retries'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/producer.rb:370:in `loop'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/producer.rb:370:in `deliver_messages_with_retries'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/producer.rb:247:in `block in deliver_messages'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/producer.rb:240:in `deliver_messages'
./myproject:38:in `block (2 levels) in run'
./myproject:33:in `each'
./myproject:33:in `block in run'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:312:in `block (3 levels) in each_batch'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:35:in `instrument'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:310:in `block (2 levels) in each_batch'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:292:in `each'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:292:in `block in each_batch'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:393:in `block in consumer_loop'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:35:in `instrument'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:392:in `consumer_loop'
/opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:289:in `each_batch'
./myproject:31:in `run'
./myproject:64:in `block in start_worker'
I, [2018-10-02T08:57:27.539172 #18366]  INFO -- : Committing offsets: my.local.topic/0:32993049
D, [2018-10-02T08:57:27.539410 #18366] DEBUG -- : Sending offset_commit API request 604 to localhost:9092
D, [2018-10-02T08:57:27.540233 #18366] DEBUG -- : Waiting for response 604 from localhost:9092
D, [2018-10-02T08:57:27.540653 #18366] DEBUG -- : Received response 604 from localhost:9092
E, [2018-10-02T08:57:27.540831 #18366] ERROR -- : Error committing offsets: Kafka::UnknownMemberId
E, [2018-10-02T08:57:27.540961 #18366] ERROR -- : Retrying to make final offsets commit (3 attempts left)
I, [2018-10-02T08:57:27.641155 #18366]  INFO -- : Committing offsets: my.local.topic/0:32993049
D, [2018-10-02T08:57:27.641367 #18366] DEBUG -- : Sending offset_commit API request 605 to localhost:9092
D, [2018-10-02T08:57:27.641606 #18366] DEBUG -- : Waiting for response 605 from localhost:9092
D, [2018-10-02T08:57:27.642350 #18366] DEBUG -- : Received response 605 from localhost:9092
E, [2018-10-02T08:57:27.642550 #18366] ERROR -- : Error committing offsets: Kafka::UnknownMemberId
E, [2018-10-02T08:57:27.642623 #18366] ERROR -- : Retrying to make final offsets commit (2 attempts left)
I, [2018-10-02T08:57:27.742746 #18366]  INFO -- : Committing offsets: my.local.topic/0:32993049
D, [2018-10-02T08:57:27.742986 #18366] DEBUG -- : Sending offset_commit API request 606 to localhost:9092
D, [2018-10-02T08:57:27.743341 #18366] DEBUG -- : Waiting for response 606 from localhost:9092
D, [2018-10-02T08:57:27.744074 #18366] DEBUG -- : Received response 606 from localhost:9092
E, [2018-10-02T08:57:27.744273 #18366] ERROR -- : Error committing offsets: Kafka::UnknownMemberId
E, [2018-10-02T08:57:27.744346 #18366] ERROR -- : Retrying to make final offsets commit (1 attempts left)
I, [2018-10-02T08:57:27.844537 #18366]  INFO -- : Committing offsets: my.local.topic/0:32993049
D, [2018-10-02T08:57:27.844771 #18366] DEBUG -- : Sending offset_commit API request 607 to localhost:9092
D, [2018-10-02T08:57:27.845012 #18366] DEBUG -- : Waiting for response 607 from localhost:9092
D, [2018-10-02T08:57:27.845779 #18366] DEBUG -- : Received response 607 from localhost:9092
E, [2018-10-02T08:57:27.846002 #18366] ERROR -- : Error committing offsets: Kafka::UnknownMemberId
I, [2018-10-02T08:57:27.846189 #18366]  INFO -- : Leaving group `myproject`
D, [2018-10-02T08:57:27.846304 #18366] DEBUG -- : Sending leave_group API request 608 to localhost:9092
D, [2018-10-02T08:57:27.846515 #18366] DEBUG -- : Waiting for response 608 from localhost:9092
D, [2018-10-02T08:57:27.847111 #18366] DEBUG -- : Received response 608 from localhost:9092
W, [2018-10-02T08:57:27.847645 #18366]  WARN -- : Restarting crashed worker logship: Kafka::ProcessingError::Kafka::ProcessingError
D, [2018-10-02T08:57:27.847773 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:321:in `rescue in block (3 levels) in each_batch'
D, [2018-10-02T08:57:27.847813 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:324:in `block (3 levels) in each_batch'
D, [2018-10-02T08:57:27.847850 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:23:in `instrument'
D, [2018-10-02T08:57:27.847887 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:35:in `instrument'
D, [2018-10-02T08:57:27.848036 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:310:in `block (2 levels) in each_batch'
D, [2018-10-02T08:57:27.848074 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:292:in `each'
D, [2018-10-02T08:57:27.848110 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:292:in `block in each_batch'
D, [2018-10-02T08:57:27.848148 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:393:in `block in consumer_loop'
D, [2018-10-02T08:57:27.848184 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:23:in `instrument'
D, [2018-10-02T08:57:27.848222 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/instrumenter.rb:35:in `instrument'
D, [2018-10-02T08:57:27.848258 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:392:in `consumer_loop'
D, [2018-10-02T08:57:27.848295 #18366] DEBUG -- : /opt/myproject/vendor/bundler/ruby/2.3.0/gems/ruby-kafka-0.7.1/lib/kafka/consumer.rb:289:in `each_batch'
D, [2018-10-02T08:57:27.848331 #18366] DEBUG -- : ./myproject:31:in `run'
D, [2018-10-02T08:57:27.848367 #18366] DEBUG -- : ./myproject:64:in `block in start_worker'
D, [2018-10-02T08:57:28.063821 #18366] DEBUG -- : Handling fetcher command: stop

```
