### ISSUE TITLE
ThreadError: can't alloc thread

### ISSUE THREAD

**Issue by lewispb** [zendesk/ruby-kafka#662]
* Version of Ruby: 2.5.1
* Version of Kafka: 0.11+
* Version of ruby-kafka: master

I've been testing master after https://github.com/zendesk/ruby-kafka/pull/654 was merged, along with master version of Karafka after https://github.com/karafka/karafka/pull/415 was merged.

We continue to see thread alloc errors:

```
Exception(most recent call first)

ThreadError: can't alloc thread
  from kafka/fetcher.rb:48:in `new'
  from kafka/fetcher.rb:48:in `start'
  from kafka/consumer.rb:390:in `consumer_loop'
  from karafka/patches/ruby_kafka.rb:15:in `consumer_loop'
  from kafka/consumer.rb:291:in `each_batch'
  from karafka/connection/client.rb:29:in `fetch_loop'
  from karafka/connection/listener.rb:39:in `fetch_loop'
  from karafka/connection/listener.rb:23:in `call'
  from karafka/fetcher.rb:19:in `block (2 levels) in call'
```

These usually follow SSL connection errors.

```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
  from kafka/ssl_socket_with_timeout.rb:68:in `connect_nonblock'
  from kafka/ssl_socket_with_timeout.rb:68:in `initialize'
  from kafka/connection.rb:124:in `new'
  from kafka/connection.rb:124:in `open'
  from kafka/connection.rb:97:in `block in send_request'
  from active_support/notifications.rb:170:in `instrument'
  from kafka/instrumenter.rb:21:in `instrument'
  from kafka/connection.rb:96:in `send_request'
  from kafka/sasl_authenticator.rb:45:in `authenticate!'
  from kafka/connection_builder.rb:27:in `build_connection'
  from kafka/broker.rb:202:in `connection'
  from kafka/broker.rb:188:in `send_request'
  from kafka/broker.rb:92:in `join_group'
  from kafka/consumer_group.rb:131:in `block in join_group'
  from active_support/notifications.rb:170:in `instrument'
  from kafka/instrumenter.rb:21:in `instrument'
  from kafka/instrumenter.rb:35:in `instrument'
  from kafka/consumer_group.rb:130:in `join_group'
  from kafka/consumer_group.rb:47:in `join'
  from kafka/consumer.rb:444:in `join_group'
  from kafka/consumer.rb:507:in `fetch_batches'
  from kafka/consumer.rb:292:in `block in each_batch'
  from karafka/patches/ruby_kafka.rb:27:in `block in consumer_loop'
  from kafka/consumer.rb:395:in `block in consumer_loop'
  from active_support/notifications.rb:170:in `instrument'
  from kafka/instrumenter.rb:21:in `instrument'
  from kafka/instrumenter.rb:35:in `instrument'
  from kafka/consumer.rb:394:in `consumer_loop'
  from karafka/patches/ruby_kafka.rb:15:in `consumer_loop'
  from kafka/consumer.rb:291:in `each_batch'
  from karafka/connection/client.rb:29:in `fetch_loop'
  from karafka/connection/listener.rb:39:in `fetch_loop'
  from karafka/connection/listener.rb:23:in `call'
  from karafka/fetcher.rb:19:in `block (2 levels) in call'
```

**Comment by mensfeld** [comment]
I briefly checked and have the same problem. Works for me and the examples from the original issue.

**Comment by mensfeld** [comment]
@lewispb something is wrong on your side. This is the output of testing against most current master with my original snippet:

```
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
2018-10-09 18:52:23 +0200
Could not connect to any of the seed brokers:
- kafka://localhost:9092: Connection refused - connect(2) for 127.0.0.1:9092
1
```

are you sure, you've updated the ruby-kafka repo?

**Comment by mensfeld** [comment]
@lewispb got it. Can reproduce. Great. Does not work as intended indeed.

**Comment by mensfeld** [comment]
Despite my first impression, all seems to work fine. Thread number is stable despite exceptions.

**Comment by nguyenquangminh0711** [comment]
Yeah. Me too. When running that code snippet, it looks like the number of thread keeps the same for a long amount of time. Is there anything special about your ruby? Which version of Ruby you are using, and could you check the Gemfile.lock to ensure the code is at latest commit in master?
cc @lewispb

**Comment by lewispb** [comment]
Thanks @nguyenquangminh0711 and @mensfeld I have double checked this with the latest version and the thread count is indeed stable, so sorry for my mistake. I think I forgot to `bundle exec` 🤦‍♂️ 

However we are still seeing plenty of thread alloc errors in production.

I will upgrade to the latest version of Karafka today and report back.

**Comment by mensfeld** [comment]
Well you see them as this patch for ruby-kafka is not yet released. Same for the retry fix in Karafka.

**Comment by nguyenquangminh0711** [comment]
Hi @dasch, could you have a look and backport that fix to 0.6.x release?

**Comment by dasch** [comment]
@nguyenquangminh0711 I can do the releasin' if you backport the fix to the `v0.6-stable` branch.

**Comment by nguyenquangminh0711** [comment]
@dasch Oh I didn't know that. Could you have a look at this PR: https://github.com/zendesk/ruby-kafka/pull/666/files?

**Comment by lewispb** [comment]
I believe this issue is resolved with the latest version of Karafka, in master. Happy for this to be closed now. Thank you all for your help!
