### ISSUE TITLE
Connection Error / Failed to fetch metadata / Errno::ETIMEDOUT: Connection timed out 

### ISSUE THREAD

**Issue by fyery-chen** [zendesk/ruby-kafka#677]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.3
* Version of Kafka: 0.10.1
* Version of ruby-kafka: 0.6.7

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
require "kafka"
require "logger"

k=Kafka.new(
  logger: Logger.new(STDOUT),
  seed_brokers: ["kafka.com:9092"],
  sasl_gssapi_principal: "kafka@kafka.com",
  sasl_gssapi_keytab: "/etc/keytabs/kafka.keytab",

k.deliver_message('abc', topic: 'fluentd')
```

###### Expected outcome

Can publish topic message to Kafka brokers successfully.

###### Actual outcome

```
I, [2017-12-06T01:05:07.922443 #6436]  INFO -- : New topics added to target list: fluentd
I, [2017-12-06T01:05:07.922520 #6436]  INFO -- : Fetching cluster metadata from kafka://kafka.example.com:9095
D, [2017-12-06T01:05:07.922582 #6436] DEBUG -- : Opening connection to kafka.example.com:9095 with client id ruby-kafka...
D, [2017-12-06T01:05:07.939300 #6436] DEBUG -- : Sending sasl_handshake API request 1 to kafka.example.com:9095
D, [2017-12-06T01:05:07.939473 #6436] DEBUG -- : Waiting for response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:07.941101 #6436] DEBUG -- : Received response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:07.957806 #6436] DEBUG -- : GSSAPI: Initializing context with kafka.example.com:9095, principal kafka@kafka.example.com
D, [2017-12-06T01:05:07.968115 #6436] DEBUG -- : Sending topic_metadata API request 2 to kafka.example.com:9095
D, [2017-12-06T01:05:07.968240 #6436] DEBUG -- : Waiting for response 2 from kafka.example.com:9095
E, [2017-12-06T01:05:17.978989 #6436] ERROR -- : Timed out while waiting for response 2
D, [2017-12-06T01:05:17.979269 #6436] DEBUG -- : Closing socket to kafka.example.com:9095
D, [2017-12-06T01:05:17.979526 #6436] DEBUG -- : Closing socket to kafka.example.com:9095
E, [2017-12-06T01:05:17.979749 #6436] ERROR -- : Failed to fetch metadata from kafka://kafka.example.com:9095: Connection error Errno::ETIMEDOUT: Connection timed out
D, [2017-12-06T01:05:17.979892 #6436] DEBUG -- : Opening connection to kafka.example.com:9095 with client id ruby-kafka...
D, [2017-12-06T01:05:18.002404 #6436] DEBUG -- : Sending sasl_handshake API request 1 to kafka.example.com:9095
D, [2017-12-06T01:05:18.002545 #6436] DEBUG -- : Waiting for response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:18.005036 #6436] DEBUG -- : Received response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:18.005136 #6436] DEBUG -- : GSSAPI: Initializing context with kafka.example.com:9095, principal kafka@kafka.example.com
D, [2017-12-06T01:05:18.013008 #6436] DEBUG -- : Closing socket to kafka.example.com:9095
/home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:286:in `fetch_cluster_info': Could not connect to any of the seed brokers: (Kafka::ConnectionError)
- kafka://kafka.example.com:9095: Connection error Errno::ETIMEDOUT: Connection timed out
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:246:in `cluster_info'
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:82:in `refresh_metadata!'
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:48:in `add_target_topics'
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:140:in `partitions_for'
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/client.rb:125:in `deliver_message'
	from test.rb:15:in `<main>'
```
There is a same issue here #498 , but I don't know why close it.

**Comment by J2RGEZ** [comment]
Can you connect to kafka using `telnet kafka.com 9092`?

**Comment by fyery-chen** [comment]
> Can you connect to kafka using e.g. `telnet kafka.com 9092`? Also, try with ruby-kafka 0.6.8 please
Yes, the connection is OK, you can see that the timeout occurred in the second response as below when sending topic_metadata API request,
```
D, [2017-12-06T01:05:07.939300 #6436] DEBUG -- : Sending sasl_handshake API request 1 to kafka.example.com:9095
D, [2017-12-06T01:05:07.939473 #6436] DEBUG -- : Waiting for response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:07.941101 #6436] DEBUG -- : Received response 1 from kafka.example.com:9095
D, [2017-12-06T01:05:07.957806 #6436] DEBUG -- : GSSAPI: Initializing context with kafka.example.com:9095, principal kafka@kafka.example.com
D, [2017-12-06T01:05:07.968115 #6436] DEBUG -- : Sending topic_metadata API request 2 to kafka.example.com:9095
D, [2017-12-06T01:05:07.968240 #6436] DEBUG -- : Waiting for response 2 from kafka.example.com:9095
E, [2017-12-06T01:05:17.978989 #6436] ERROR -- : Timed out while waiting for response 2
```

**Comment by nguyenquangminh0711** [comment]
Another issue with using SASL authentication method. There are some other issues with that, and it looks like they all come from fluentd intergration. I'm suspect that the SASL authenticating module is having a problem. That module is contributed long before by other contributor. I haven't used this authentication method personally. But since the number of issues related to that is increasing, I will try out to see what's happening.

Thanks for reporting this issue ❤️
