### ISSUE TITLE
Can't produce messages with over 98,295 bytes in ruby-kafka 0.7.1+

### ISSUE THREAD

**Issue by jturkel** [zendesk/ruby-kafka#680]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.5.1
* Version of Kafka: 1.1.1
* Version of ruby-kafka: 0.7.1, 0.7.2, 0.7.3 and master

###### Steps to reproduce

There's a failing test on https://github.com/zendesk/ruby-kafka/compare/master...jturkel:feature/big-message-failure but pasting the relevant bits here:

```ruby
kafka = Kafka.new(...)
producer = kafka.producer(max_retries: 3, retry_backoff: 1)

value = 'a' * 98296
producer.produce(value, topic: topic, partition: 0)
producer.deliver_messages

message = kafka.fetch_messages(topic: topic, partition: 0, offset: :earliest).last

expect(message.value).to eq value
```

###### Expected outcome

The test should pass like it does in ruby-kafka <= 0.7.0.

###### Actual outcome

The test fails with the following error:

```
     Kafka::DeliveryFailed:
       Failed to send messages to f2e93c50d3490054-topic-295d4aee-8cdc-41aa-ad0d-8a0686a565b9/0
     # ./lib/kafka/producer.rb:412:in `deliver_messages_with_retries'
     # ./lib/kafka/producer.rb:247:in `block in deliver_messages'
     # /Users/jturkel/.rvm/gems/ruby-2.5.1@ruby-kafka/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
     # /Users/jturkel/.rvm/gems/ruby-2.5.1@ruby-kafka/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
     # /Users/jturkel/.rvm/gems/ruby-2.5.1@ruby-kafka/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
     # ./lib/kafka/instrumenter.rb:21:in `instrument'
     # ./lib/kafka/producer.rb:240:in `deliver_messages'
     # ./spec/functional/producer_spec.rb:135:in `block (2 levels) in <top (required)>'
```

Here is the corresponding log output (with most of the message value elided for readability):
```
I, [2018-11-05T21:55:23.811246 #19885]  INFO -- : Fetching cluster metadata from kafka://localhost:9092
D, [2018-11-05T21:55:23.811372 #19885] DEBUG -- : Opening connection to localhost:9092 with client id test...
D, [2018-11-05T21:55:23.813686 #19885] DEBUG -- : Sending topic_metadata API request 1 to localhost:9092
D, [2018-11-05T21:55:23.813899 #19885] DEBUG -- : Waiting for response 1 from localhost:9092
D, [2018-11-05T21:55:23.815273 #19885] DEBUG -- : Received response 1 from localhost:9092
D, [2018-11-05T21:55:23.815349 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"localhost", :api=>:topic_metadata, :request_size=>18, :response_size=>45, :client_id=>"test"}
I, [2018-11-05T21:55:23.815382 #19885]  INFO -- : Discovered cluster metadata; nodes: docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:23.815409 #19885] DEBUG -- : Closing socket to localhost:9092
I, [2018-11-05T21:55:23.815462 #19885]  INFO -- : Creating topic `a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85` using controller broker docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:23.815520 #19885] DEBUG -- : Opening connection to docker.local.host:9092 with client id test...
D, [2018-11-05T21:55:23.816680 #19885] DEBUG -- : Sending create_topics API request 1 to docker.local.host:9092
D, [2018-11-05T21:55:23.816799 #19885] DEBUG -- : Waiting for response 1 from docker.local.host:9092
D, [2018-11-05T21:55:23.842434 #19885] DEBUG -- : Received response 1 from docker.local.host:9092
D, [2018-11-05T21:55:23.842566 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"docker.local.host", :api=>:create_topics, :request_size=>97, :response_size=>71, :client_id=>"test"}
I, [2018-11-05T21:55:23.842631 #19885]  INFO -- : New topics added to target list: a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85
I, [2018-11-05T21:55:23.842670 #19885]  INFO -- : Fetching cluster metadata from kafka://localhost:9092
D, [2018-11-05T21:55:23.842739 #19885] DEBUG -- : Opening connection to localhost:9092 with client id test...
D, [2018-11-05T21:55:23.843998 #19885] DEBUG -- : Sending topic_metadata API request 1 to localhost:9092
D, [2018-11-05T21:55:23.844114 #19885] DEBUG -- : Waiting for response 1 from localhost:9092
D, [2018-11-05T21:55:23.845888 #19885] DEBUG -- : Received response 1 from localhost:9092
D, [2018-11-05T21:55:23.845973 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"localhost", :api=>:topic_metadata, :request_size=>79, :response_size=>191, :client_id=>"test"}
I, [2018-11-05T21:55:23.846008 #19885]  INFO -- : Discovered cluster metadata; nodes: docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:23.846070 #19885] DEBUG -- : Closing socket to localhost:9092
I, [2018-11-05T21:55:23.846121 #19885]  INFO -- : Topic `a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85` was created
D, [2018-11-05T21:55:24.352226 #19885] DEBUG -- : Instrumentation event `produce_message.producer.kafka`: {:value=>"aaa...aaa", :key=>nil, :topic=>"a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85", :create_time=>2018-11-05 21:55:24 -0500, :message_size=>98296, :buffer_size=>1, :max_buffer_size=>1000, :client_id=>"test"}
I, [2018-11-05T21:55:24.352579 #19885]  INFO -- : New topics added to target list: a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85
I, [2018-11-05T21:55:24.352653 #19885]  INFO -- : Fetching cluster metadata from kafka://localhost:9092
D, [2018-11-05T21:55:24.352755 #19885] DEBUG -- : Opening connection to localhost:9092 with client id test...
D, [2018-11-05T21:55:24.354426 #19885] DEBUG -- : Sending topic_metadata API request 1 to localhost:9092
D, [2018-11-05T21:55:24.354584 #19885] DEBUG -- : Waiting for response 1 from localhost:9092
D, [2018-11-05T21:55:24.357044 #19885] DEBUG -- : Received response 1 from localhost:9092
D, [2018-11-05T21:55:24.357169 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"localhost", :api=>:topic_metadata, :request_size=>79, :response_size=>191, :client_id=>"test"}
I, [2018-11-05T21:55:24.357228 #19885]  INFO -- : Discovered cluster metadata; nodes: docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:24.357260 #19885] DEBUG -- : Closing socket to localhost:9092
D, [2018-11-05T21:55:24.357424 #19885] DEBUG -- : Current leader for a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 is node docker.local.host:9092 (node_id=1001)
I, [2018-11-05T21:55:24.357483 #19885]  INFO -- : Sending 1 messages to docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:24.357566 #19885] DEBUG -- : Opening connection to docker.local.host:9092 with client id test...
D, [2018-11-05T21:55:24.359034 #19885] DEBUG -- : Sending produce API request 1 to docker.local.host:9092
D, [2018-11-05T21:55:24.376626 #19885] DEBUG -- : Waiting for response 1 from docker.local.host:9092
D, [2018-11-05T21:55:24.379395 #19885] DEBUG -- : Received response 1 from docker.local.host:9092
D, [2018-11-05T21:55:24.379483 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"docker.local.host", :api=>:produce, :request_size=>98465, :response_size=>99, :client_id=>"test"}
D, [2018-11-05T21:55:24.379576 #19885] DEBUG -- : Instrumentation event `topic_error.producer.kafka`: {:topic=>"a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85", :exception=>["Kafka::CorruptMessage", "Kafka::CorruptMessage"], :client_id=>"test"}
E, [2018-11-05T21:55:24.379676 #19885] ERROR -- : Corrupt message when writing to a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 on docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:24.379717 #19885] DEBUG -- : Instrumentation event `send_messages.producer.kafka`: {:client_id=>"test", :message_count=>1, :sent_message_count=>0}
W, [2018-11-05T21:55:24.379745 #19885]  WARN -- : Failed to send all messages; attempting retry 1 of 3 after 1s
D, [2018-11-05T21:55:25.383773 #19885] DEBUG -- : Current leader for a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 is node docker.local.host:9092 (node_id=1001)
I, [2018-11-05T21:55:25.383957 #19885]  INFO -- : Sending 1 messages to docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:25.384132 #19885] DEBUG -- : Sending produce API request 2 to docker.local.host:9092
D, [2018-11-05T21:55:25.402808 #19885] DEBUG -- : Waiting for response 2 from docker.local.host:9092
D, [2018-11-05T21:55:25.404709 #19885] DEBUG -- : Received response 2 from docker.local.host:9092
D, [2018-11-05T21:55:25.404787 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"docker.local.host", :api=>:produce, :request_size=>98465, :response_size=>99, :client_id=>"test"}
D, [2018-11-05T21:55:25.404893 #19885] DEBUG -- : Instrumentation event `topic_error.producer.kafka`: {:topic=>"a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85", :exception=>["Kafka::CorruptMessage", "Kafka::CorruptMessage"], :client_id=>"test"}
E, [2018-11-05T21:55:25.404986 #19885] ERROR -- : Corrupt message when writing to a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 on docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:25.405024 #19885] DEBUG -- : Instrumentation event `send_messages.producer.kafka`: {:client_id=>"test", :message_count=>1, :sent_message_count=>0}
W, [2018-11-05T21:55:25.405051 #19885]  WARN -- : Failed to send all messages; attempting retry 2 of 3 after 1s
D, [2018-11-05T21:55:26.410013 #19885] DEBUG -- : Current leader for a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 is node docker.local.host:9092 (node_id=1001)
I, [2018-11-05T21:55:26.410099 #19885]  INFO -- : Sending 1 messages to docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:26.410172 #19885] DEBUG -- : Sending produce API request 3 to docker.local.host:9092
D, [2018-11-05T21:55:26.425418 #19885] DEBUG -- : Waiting for response 3 from docker.local.host:9092
D, [2018-11-05T21:55:26.427203 #19885] DEBUG -- : Received response 3 from docker.local.host:9092
D, [2018-11-05T21:55:26.427276 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"docker.local.host", :api=>:produce, :request_size=>98465, :response_size=>99, :client_id=>"test"}
D, [2018-11-05T21:55:26.427365 #19885] DEBUG -- : Instrumentation event `topic_error.producer.kafka`: {:topic=>"a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85", :exception=>["Kafka::CorruptMessage", "Kafka::CorruptMessage"], :client_id=>"test"}
E, [2018-11-05T21:55:26.427451 #19885] ERROR -- : Corrupt message when writing to a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 on docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:26.427485 #19885] DEBUG -- : Instrumentation event `send_messages.producer.kafka`: {:client_id=>"test", :message_count=>1, :sent_message_count=>0}
W, [2018-11-05T21:55:26.427511 #19885]  WARN -- : Failed to send all messages; attempting retry 3 of 3 after 1s
D, [2018-11-05T21:55:27.432630 #19885] DEBUG -- : Current leader for a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 is node docker.local.host:9092 (node_id=1001)
I, [2018-11-05T21:55:27.432776 #19885]  INFO -- : Sending 1 messages to docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:27.432906 #19885] DEBUG -- : Sending produce API request 4 to docker.local.host:9092
D, [2018-11-05T21:55:27.451079 #19885] DEBUG -- : Waiting for response 4 from docker.local.host:9092
D, [2018-11-05T21:55:27.452828 #19885] DEBUG -- : Received response 4 from docker.local.host:9092
D, [2018-11-05T21:55:27.452913 #19885] DEBUG -- : Instrumentation event `request.connection.kafka`: {:broker_host=>"docker.local.host", :api=>:produce, :request_size=>98465, :response_size=>99, :client_id=>"test"}
D, [2018-11-05T21:55:27.453036 #19885] DEBUG -- : Instrumentation event `topic_error.producer.kafka`: {:topic=>"a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85", :exception=>["Kafka::CorruptMessage", "Kafka::CorruptMessage"], :client_id=>"test"}
E, [2018-11-05T21:55:27.453135 #19885] ERROR -- : Corrupt message when writing to a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0 on docker.local.host:9092 (node_id=1001)
D, [2018-11-05T21:55:27.453173 #19885] DEBUG -- : Instrumentation event `send_messages.producer.kafka`: {:client_id=>"test", :message_count=>1, :sent_message_count=>0}
E, [2018-11-05T21:55:27.453202 #19885] ERROR -- : Failed to send all messages; keeping remaining messages in buffer
D, [2018-11-05T21:55:27.453319 #19885] DEBUG -- : Instrumentation event `deliver_messages.producer.kafka`: {:client_id=>"test", :message_count=>1, :attempts=>4, :delivered_message_count=>0, :exception=>["Kafka::DeliveryFailed", "Failed to send messages to a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0"], :exception_object=>#<Kafka::DeliveryFailed: Failed to send messages to a65509ae0af77a78-topic-7698f96c-51e1-4577-9e3d-56cf5931da85/0>}
I, [2018-11-05T21:55:27.453401 #19885]  INFO -- : Disconnecting broker 1001
D, [2018-11-05T21:55:27.453428 #19885] DEBUG -- : Closing socket to docker.local.host:9092
I, [2018-11-05T21:55:27.453479 #19885]  INFO -- : Disconnecting broker 1001
D, [2018-11-05T21:55:27.453504 #19885] DEBUG -- : Closing socket to docker.local.host:9092
```

**Comment by nguyenquangminh0711** [comment]
Hi @jturkel, it looks like the limitation is from Kafka itself. From version 0.11.x, Kafka introduces new record batch format, which has a limit of size of each batch. Before ruby-kafka version 0.7.x, ruby-kafka uses legacy "message set" encoding format. This format is still supported by Kafka to ensure backward compatibility, but lack of new fancy features; and of course the limit is not enstricted. From 0.7.x, ruby-kafka drops the supporting of that legacy format and replace it by new record batch format. That could be the reason for this error. Could you double check your global configuration`max.message.bytes` or per-topic configuration with the same name to verify my theory? You can use ruby-kafka to fetch topic configuration by

```ruby
client.describe_topic('topic_a', ['max.message.bytes'])
```

If that's the source of problem, the solution is to update Kafka's configuration. Or you can use ruby-kafka to update per-topic configruation with:

```ruby
client.alter_topic('topic_a', 'max_message.bytes' => 100_000)
```

**Comment by jturkel** [comment]
I double checked and the topic's `max.message.bytes` is 1,000,012 but the message value is only 98,296 bytes. Looks like that's not the problem :(

**Comment by nguyenquangminh0711** [comment]
I see. I have just re-produce it in my local environment and debugging the issue.
