### ISSUE TITLE
Calling describe_group state method results in Kafka::ConnectionError while CG state is transitioning

### ISSUE THREAD

**Issue by dezka** [zendesk/ruby-kafka#755]
* Version of Ruby: 2.5.1p57
* Version of Kafka: 2.1
* Version of ruby-kafka: 0.7.8

###### Steps to reproduce

```ruby
require 'kafka'

group = 'dezka-consumer-group-Test1'
hosts = ["kafka1:9092"]

logger = Logger.new('/tmp/kafka.out')

kafka = Kafka.new(hosts, logger: logger)

puts kafka.describe_group(group).state
```

Given the `dezka-consumer-group-Test1` state is currently `Stable` with two consumers, while running the code above, trigger a consumer group rebalance to force the state to change by shutting down one of the consumers.

###### Expected outcome

The state output should change from `Stable` to `PreparingRebalance` / `CompletingRebalance` and then `Stable` (since one consumer is left in the group).

###### Actual outcome

The following exception is thrown _while_ the transition of state is happening:

```
Traceback (most recent call last):
	6: from client.rb:10:in `<main>'
	5: from /Users/dbielinski/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.8/lib/kafka/client.rb:615:in `describe_group'
	4: from /Users/dbielinski/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.8/lib/kafka/cluster.rb:249:in `describe_group'
	3: from /Users/dbielinski/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.8/lib/kafka/broker.rb:164:in `describe_groups'
	2: from /Users/dbielinski/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.8/lib/kafka/broker.rb:200:in `send_request'
	1: from /Users/dbielinski/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.8/lib/kafka/connection.rb:84:in `send_request'
/Users/dbielinski/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.8/lib/kafka/connection.rb:116:in `rescue in send_request': Connection error EOFError: EOFError (Kafka::ConnectionError)
```

Logger output:

```
D, [2019-07-10T12:06:11.555481 #31059] DEBUG -- : Getting group coordinator for `dezka-consumer-group-Test1`
I, [2019-07-10T12:06:11.555586 #31059]  INFO -- : Fetching cluster metadata from kafka://kafka1:9092
D, [2019-07-10T12:06:11.555656 #31059] DEBUG -- : [topic_metadata] Opening connection to kafka1:9092 with client id ruby-kafka...
D, [2019-07-10T12:06:11.576236 #31059] DEBUG -- : [topic_metadata] Sending topic_metadata API request 1 to kafka1:9092
D, [2019-07-10T12:06:11.576439 #31059] DEBUG -- : [topic_metadata] Waiting for response 1 from kafka1:9092
D, [2019-07-10T12:06:11.597661 #31059] DEBUG -- : [topic_metadata] Received response 1 from kafka1:9092
I, [2019-07-10T12:06:11.597804 #31059]  INFO -- : Discovered cluster metadata; nodes: kafka1:9092 (node_id=0)
D, [2019-07-10T12:06:11.597861 #31059] DEBUG -- : Closing socket to kafka1:9092
D, [2019-07-10T12:06:11.598047 #31059] DEBUG -- : [find_coordinator] Opening connection to kafka1:9092 with client id ruby-kafka...
D, [2019-07-10T12:06:11.619460 #31059] DEBUG -- : [find_coordinator] Sending find_coordinator API request 1 to kafka1:9092
D, [2019-07-10T12:06:11.619678 #31059] DEBUG -- : [find_coordinator] Waiting for response 1 from kafka1:9092
D, [2019-07-10T12:06:11.642215 #31059] DEBUG -- : [find_coordinator] Received response 1 from kafka1:9092
D, [2019-07-10T12:06:11.642358 #31059] DEBUG -- : Coordinator for `dezka-consumer-group-Test1` is 0. Connecting...
D, [2019-07-10T12:06:11.642408 #31059] DEBUG -- : Connected to coordinator: kafka1:9092 (node_id=0) for `dezka-consumer-group-Test1`
D, [2019-07-10T12:06:11.642510 #31059] DEBUG -- : [unknown] Sending unknown API request 2 to kafka1:9092
D, [2019-07-10T12:06:11.642628 #31059] DEBUG -- : [unknown] Waiting for response 2 from kafka1:9092
D, [2019-07-10T12:06:11.664570 #31059] DEBUG -- : [unknown] Closing socket to kafka1:9092
D, [2019-07-10T12:06:11.664733 #31059] DEBUG -- : Closing socket to kafka1:9092
```

After the state transition is finished (typically the second after the above exception) you will then see the state output be `Stable` as expected after partitions are reassigned to the remaining consumer(s). This seems to only happen if you run the above code at the exact time a state transition is happening.

**Comment by yasseur1007** [comment]
Hi! 
I'm facing the same issue, would be nice some takes a look at it :/

kafka version: 2.11_0.10.2.0
ruby-kafka: 1.1.0

Codebase:
```
require "kafka"
require 'logger'

logger = Logger.new(STDOUT)
logger.level = Logger::DEBUG

sourceKafka = Kafka.new(["localhost:9092"], logger: logger)

sourceGroups = sourceKafka.groups
sourceGroupsoffsets = {}
sourceGroups.each do |g|
  puts sourceKafka.fetch_group_offsets(g)
end

```

```
I, [2020-07-02T23:23:19.015006 #35357]  INFO -- : Fetching cluster metadata from kafka://localhost:9092
D, [2020-07-02T23:23:19.015186 #35357] DEBUG -- : [topic_metadata] Opening connection to localhost:9092 with client id ruby-kafka...
D, [2020-07-02T23:23:19.017799 #35357] DEBUG -- : [topic_metadata] Sending topic_metadata API request 1 to localhost:9092
D, [2020-07-02T23:23:19.018064 #35357] DEBUG -- : [topic_metadata] Waiting for response 1 from localhost:9092
D, [2020-07-02T23:23:19.023027 #35357] DEBUG -- : [topic_metadata] Received response 1 from localhost:9092
I, [2020-07-02T23:23:19.023158 #35357]  INFO -- : Discovered cluster metadata; nodes: localhost:9092 (node_id=1001)
D, [2020-07-02T23:23:19.023212 #35357] DEBUG -- : Closing socket to localhost:9092
D, [2020-07-02T23:23:19.023370 #35357] DEBUG -- : [unknown] Opening connection to localhost:9092 with client id ruby-kafka...
D, [2020-07-02T23:23:19.025104 #35357] DEBUG -- : [unknown] Sending unknown API request 1 to localhost:9092
D, [2020-07-02T23:23:19.025392 #35357] DEBUG -- : [unknown] Waiting for response 1 from localhost:9092
D, [2020-07-02T23:23:19.035373 #35357] DEBUG -- : [unknown] Received response 1 from localhost:9092
D, [2020-07-02T23:23:19.035500 #35357] DEBUG -- : Getting group coordinator for `read_half`
D, [2020-07-02T23:23:19.035634 #35357] DEBUG -- : [find_coordinator] Sending find_coordinator API request 2 to localhost:9092
D, [2020-07-02T23:23:19.035934 #35357] DEBUG -- : [find_coordinator] Waiting for response 2 from localhost:9092
D, [2020-07-02T23:23:19.040258 #35357] DEBUG -- : [find_coordinator] Closing socket to localhost:9092
D, [2020-07-02T23:23:19.040353 #35357] DEBUG -- : Closing socket to localhost:9092
E, [2020-07-02T23:23:19.040441 #35357] ERROR -- : Failed to get coordinator info from localhost:9092 (node_id=1001): Connection error EOFError: EOFError
Traceback (most recent call last):
	6: from show-missing-group-offsets.rb:128:in `<main>'
	5: from show-missing-group-offsets.rb:128:in `each'
	4: from show-missing-group-offsets.rb:129:in `block in <main>'
	3: from /Users/yassin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-1.1.0/lib/kafka/client.rb:655:in `fetch_group_offsets'
	2: from /Users/yassin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-1.1.0/lib/kafka/cluster.rb:294:in `fetch_group_offsets'
	1: from /Users/yassin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-1.1.0/lib/kafka/cluster.rb:125:in `get_group_coordinator'
/Users/yassin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-kafka-1.1.0/lib/kafka/cluster.rb:504:in `get_coordinator': Failed to find coordinator (Kafka::Error)
```
