### ISSUE TITLE
certificate verify failed (unspecified certificate verification error)

### ISSUE THREAD

**Issue by bradurani** [zendesk/ruby-kafka#778]
* Version of Ruby: ruby 2.6.3p62
* Version of Kafka: 2.2.1
* Version of ruby-kafka: 0.7.10

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

I'm connecting to Heroku managed Kafka supplying `:ssl_ca_cert`, `:ssl_client_cert` and `:ssl_client_cert_key`. On `ruby-kafka 0.6.7` it works fine. When I upgrade to `0.7.10` I get 

```
[1] pry(#<ProcoreKafka::Producer::AsyncClient>)> I, [2019-09-16T17:11:13.690007 #21909]  INFO -- : [Producer ] New topics added to target list: white-925.firehose_testing
I, [2019-09-16T17:11:13.690161 #21909]  INFO -- : [Producer ] Fetching cluster metadata from kafka+ssl://ec2-52-200-255-3.compute-1.amazonaws.com:9096                 
D, [2019-09-16T17:11:13.690393 #21909] DEBUG -- : [Producer ] [topic_metadata] Opening connection to ec2-52-200-255-3.compute-1.amazonaws.com:9096 with client id procore...
D, [2019-09-16T17:11:13.836775 #21909] DEBUG -- : [Producer ] Closing socket to ec2-52-200-255-3.compute-1.amazonaws.com:9096                                          
E, [2019-09-16T17:11:13.836988 #21909] ERROR -- : [Producer ] Unexpected Kafka error OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
/home/burani/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in `connect_nonblock'                            
/home/burani/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in `initialize'        
```
Any idea what changed?

**Comment by tjwp** [comment]
With Heroku Kafka you'll need to specify the `verify_hostname` option as false. The verification was introduced in 0.7.7, and the option exposed in 0.7.8.

**Comment by bradurani** [comment]
Thanks!
