### ISSUE TITLE
TypeError: no implicit conversion of nil into Integer while trying to listen to specific Topic

### ISSUE THREAD

**Issue by Kutomore** [zendesk/ruby-kafka#798]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.3.7
* Version of Kafka: 2.2
* Version of ruby-kafka: 0.7.6

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

I'm trying to connec to three different topics, I can easily connect to two of them and listen with no issue, but on the third one I get the following stack error:

```
TypeError: no implicit conversion of nil into Integer
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:57:in `pack'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:57:in `write_int32'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82:in `each'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82:in `write_array'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82:in `each'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82:in `write_array'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:55:in `encode'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/request_message.rb:22:in `encode'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:178:in `encode_with'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:165:in `write_request'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:104:in `block in send_request'
  from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:21:in `instrument'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:97:in `send_request'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/broker.rb:188:in `send_request'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/broker.rb:54:in `fetch_messages'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:81:in `block in execute'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:71:in `each'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:71:in `flat_map'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:71:in `execute'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:201:in `fetch_batches'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:157:in `step'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:111:in `loop'
  from /usr/local/bundle/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:56:in `block in start'
```

And I can't quite figure out why is it happening, has anyone had an similar issue?

###### Expected outcome

I would start receiving the messages like with the other topics I use.

###### Actual outcome

I got the error mentioned above

**Comment by GrantBirki** [comment]
I do not have the most useful feedback here but I will share anyways. I hit the same bug when upgrading a lot of features on a Kafka consumer. The consumer was subscribed to **three** different topics (exactly as described above). The consumer was a service running in k8s, in a Docker container.

I sat puzzled with this bug for a while. Eventually I just tried restarting the app and the consumer came online without issues and the error went away.

This was really odd so I tried with multiple other consumers. These consumers were only subscribed to one topic each. The also encountered the same problem when joining the topics for the first time... and the error was resolved in the same way, by restarting.

Sometimes computers are lame.
