### ISSUE TITLE
Issue with `max_buffer_bytesize` & Kafka::MessageSizeTooLarge

### ISSUE THREAD

**Issue by ransombriggs** [zendesk/ruby-kafka#807]
If this is a bug report, please fill out the following:

* Version of Ruby: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
* Version of Kafka: https://www.apache.org/dist/kafka/2.2.0/kafka_2.12-2.2.0.tgz
* Version of ruby-kafka: master

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

Sorry about the odd setup, but I took the number + size of messages from an error we ran into in production and dropped them in the test and scrubbed them to recreate the specific issue we ran into in production.

```ruby
$:.unshift File.join(File.dirname(__FILE__), 'lib')

require "kafka"

lengths = [3064, 2424, 2700, 2660, 2468, 2660, 2532, 2488, 3044, 2444, 2660, 2424, 2660, 3364, 2508, 3532, 2532, 3300, 2488, 2572, 2700, 3276, 2508, 2424, 2788, 2508, 2424, 2468, 2532, 3404, 2596, 3084, 2596, 2828, 2444, 2488, 2660, 2212, 3940, 3556, 2636, 2660, 2424, 2424, 2424, 2596, 2424, 2444, 2444, 4004, 3940, 3320, 3128, 2872, 2744, 2572, 2828, 2680, 2468, 2468, 2532, 2744, 2936, 2660, 2488, 2552, 2636, 2872, 2660, 2424, 2508, 2724, 2488, 2552, 2468, 2424, 2744, 2468, 3256, 2552, 2552, 2468, 2508, 2444, 2444, 2252, 3064, 2552, 2444, 2532, 3064, 2468, 2508, 2572, 2488, 2724, 2636, 2744, 2552, 2532, 3640, 2552, 2468, 2444, 2468, 2572, 2872, 2916, 2892, 2980, 2744, 2596, 2424, 2636, 2488, 3064, 4132, 2488, 2680, 2552, 3084, 2764, 3256, 2596, 2616, 2744, 2444, 2616, 7544, 2488, 2444, 2532, 2552, 2444, 2444, 2892, 2340, 2424, 2852, 2552, 2788, 2572, 2572, 2552, 2700, 2444, 2444, 2232, 3340, 2508, 2660, 3852, 2808, 2488, 3084, 3468, 2828, 2680, 2360, 2808, 2424, 2636, 2616, 2552, 3020, 2572, 2596, 2424, 2468, 2680, 2508, 2596, 2424, 2552, 3064, 3064, 3364, 3428, 2532, 2444, 2468, 2488, 2552, 2828, 2724, 2424, 2468, 3064, 3364, 3320, 2508, 2188, 2700, 2744, 2532, 3084, 2424, 2616, 2660, 2552, 2468, 2424, 2468, 2700, 2596, 2424, 2444, 2724, 2724, 3108, 2276, 2660, 2424, 2444, 3128, 5644, 2508, 3128, 2424, 2468, 2552, 2444, 2040, 2724, 4044, 2828, 2700, 2532, 2552, 2424, 2468, 2488, 2724, 3128, 2744, 2596, 2552, 2444, 2532, 3148, 2788, 2660, 2764, 2764, 2596, 2636, 2444, 2424, 2532, 2488, 2764, 2444, 2660, 2148, 2660, 2636, 2508, 2700, 2552, 3428, 2616, 2444, 3084, 2188, 2424, 2764, 2508, 3620, 2488, 2508, 3300, 3340, 2596, 2508, 2552, 2040, 3064, 2956, 2488, 2532, 2552, 2552, 2424, 2468, 2468, 2444, 2444, 2828, 2808, 2572, 2488, 2572, 2444, 2552, 2508, 2872, 2424, 2660, 2916, 2532, 2488, 3064, 2660, 2572, 2488, 2488, 2424, 2616, 2636, 2764, 2744, 2700, 2552, 2724, 2424, 2444, 2636, 2660, 2660, 2488, 2424, 2788, 4172, 2424, 2660, 2700, 3108, 2852, 3148, 2572, 2488, 2444, 2444, 2596, 2596, 2636, 2424, 3404, 2572, 3512, 2532, 2680, 2444, 2508, 3108, 3108, 2572, 2956, 2424, 2424, 2468, 3212, 2700, 2828, 2572, 2424, 2872, 2744, 2508, 2572, 2508, 2552, 2552, 2488, 2872, 2700, 2488, 2616, 2660]

messages = lengths.map {|length| "0" * length}

kafka = ::Kafka.new(seed_brokers: "kafka://127.0.0.1:9092")
producer = kafka.producer(max_buffer_bytesize: 1_000_000)

messages.each do |message|
  producer.produce(message, topic: "topic", partition: 0)
end

puts "producer.buffer_bytesize: #{producer.buffer_bytesize}"

producer.deliver_messages
```

###### Expected outcome

What you thought would happen when running the example.

```ruby
-> % ruby issue.rb  
Traceback (most recent call last):
	4: from issue.rb:12:in `<main>'
	3: from issue.rb:12:in `each'
	2: from issue.rb:13:in `block in <main>'
	1: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/producer.rb:210:in `produce'
/home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/producer.rb:520:in `buffer_overflow': Cannot produce to topic, max buffer bytesize (1000000 bytes) reached (Kafka::BufferOverflow)
```

###### Actual outcome

What actually happened.

```ruby
-> % ruby issue.rb  
producer.buffer_bytesize: 998072
Traceback (most recent call last):
	20: from issue.rb:18:in `<main>'
	19: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/producer.rb:249:in `deliver_messages'
	18: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/instrumenter.rb:23:in `instrument'
	17: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/producer.rb:256:in `block in deliver_messages'
	16: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/producer.rb:393:in `deliver_messages_with_retries'
	15: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/producer.rb:393:in `loop'
	14: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/producer.rb:405:in `block in deliver_messages_with_retries'
	13: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/produce_operation.rb:53:in `execute'
	12: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/instrumenter.rb:23:in `instrument'
	11: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/produce_operation.rb:62:in `block in execute'
	10: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/produce_operation.rb:105:in `send_buffered_messages'
	 9: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/produce_operation.rb:105:in `each'
	 8: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/produce_operation.rb:133:in `block in send_buffered_messages'
	 7: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/produce_operation.rb:144:in `handle_response'
	 6: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/protocol/produce_response.rb:34:in `each_partition'
	 5: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/protocol/produce_response.rb:34:in `each'
	 4: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/protocol/produce_response.rb:35:in `block in each_partition'
	 3: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/protocol/produce_response.rb:35:in `each'
	 2: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/protocol/produce_response.rb:36:in `block (2 levels) in each_partition'
	 1: from /home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/produce_operation.rb:153:in `block in handle_response'
/home/rbriggs/src/github.com/zendesk/ruby-kafka/lib/kafka/protocol.rb:160:in `handle_error': Kafka::MessageSizeTooLarge (Kafka::MessageSizeTooLarge)
```

###### Explanation

We have hit `Kafka::MessageSizeTooLarge` in the past because of partition imbalance.  There is a kafka configuration `message.max.bytes` which limits the maximum byte size per produce request, the default of which is `1000012` according to [the documentation](https://kafka.apache.org/documentation/).  To try and prevent this we set our max buffer size to `1_000_000` to get under this kafka server limit.

We recently received this error again because the `producer.buffer_bytesize` does not match the actual byte size that is submitted to kafka.  It took some time to figure this out because almost all the time compression kept us under this limit, we just happened to hit a combination of data that did not compress well enough.  I took the compression out of the example to keep things simpler.

Ideally the `buffer_bytesize` would match the byte size of the message that would go to kafka.  Right now we trap `Kafka::BufferOverflow` errors and flush, but since the byte size in the example is already too large we cannot successfully flush the buffer.  We have fixed this temporarily by reducing max_buffer_bytesize by the `max_buffer_size` and a constant, but it is not a great heuristic.

**Comment by dasch** [comment]
Can you take a stab at a more accurate heuristic for the actual message size?
