### ISSUE TITLE
unable to require kafka/prometheus

### ISSUE THREAD

**Issue by konfortes** [zendesk/ruby-kafka#831]
* Version of Ruby: 2.4.2
* Version of Kafka: irrelevant
* Version of ruby-kafka: 0.7.10
* Version of prometheus-client: 0.10.0

###### Steps to reproduce

```ruby
require 'kafka/prometheus'
```

###### Expected outcome

kafka/prometheus is required successfully

###### Actual outcome

```bash
2.4.2 :002 > require 'kafka/prometheus'
ArgumentError: wrong number of arguments (given 2, expected 1)
        from /Users/ronenkonfortes/.rvm/gems/ruby-2.4.2/gems/prometheus-client-0.10.0/lib/prometheus/client/registry.rb:40:in `counter'
        from /Users/ronenkonfortes/.rvm/gems/ruby-2.4.2/gems/ruby-kafka-0.7.10/lib/kafka/prometheus.rb:45:in `initialize'
        from /Users/ronenkonfortes/.rvm/gems/ruby-2.4.2/gems/activesupport-5.2.4.3/lib/active_support/subscriber.rb:30:in `new'
        from /Users/ronenkonfortes/.rvm/gems/ruby-2.4.2/gems/activesupport-5.2.4.3/lib/active_support/subscriber.rb:30:in `attach_to'
        from /Users/ronenkonfortes/.rvm/gems/ruby-2.4.2/gems/ruby-kafka-0.7.10/lib/kafka/prometheus.rb:34:in `start'
        from /Users/ronenkonfortes/.rvm/gems/ruby-2.4.2/gems/ruby-kafka-0.7.10/lib/kafka/prometheus.rb:317:in `<top (required)>'
        from /Users/ronenkonfortes/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/ronenkonfortes/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from (irb):2
        from /Users/ronenkonfortes/.rvm/rubies/ruby-2.4.2/bin/irb:11:in `<main>'
```

**Comment by konfortes** [comment]
just noticed it was fixed in later release, sorry
