### ISSUE TITLE
Unable to start consumer with remote Kafka Broker, keep getting Kafka::InvalidReplicationFactor error

### ISSUE THREAD

**Issue by rishabhsinghvi** [zendesk/ruby-kafka#861]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.6.3
* Version of Kafka: 2.6.0
* Version of ruby-kafka: 1.2.0

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
kafka = Kafka.new(...)
consumer = kafka.consumer(group_id: 'il-consumer')
consumer.subscribe(ENV['PROD_TOPIC'], start_from_beginning: false)

consumer.each_message do |message|
        puts message.value
end
```

###### Expected outcome

The consumer would start, and listening to messages coming from a remote Kafka Broker. 
###### Actual outcome
```

Traceback (most recent call last):
        19: from InstrumentationLayerConsumer.rb:65:in `<main>'
        18: from InstrumentationLayerConsumer.rb:54:in `main'
        17: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer.rb:222:in `each_message'
        16: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer.rb:417:in `consumer_loop'
        15: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/instrumenter.rb:35:in `instrument'
        14: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/instrumenter.rb:23:in `instrument'
        13: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer.rb:419:in `block in consumer_loop'
        12: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer.rb:223:in `block in each_message'
        11: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer.rb:546:in `fetch_batches'
        10: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer.rb:475:in `join_group'
         9: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer_group.rb:49:in `join'
         8: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/consumer_group.rb:183:in `synchronize'
         7: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/round_robin_assignment_strategy.rb:27:in `assign'
         6: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/round_robin_assignment_strategy.rb:27:in `flat_map'
         5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
         4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
         3: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/round_robin_assignment_strategy.rb:29:in `block in assign'
         2: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/cluster.rb:183:in `partitions_for'
         1: from /Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/protocol/metadata_response.rb:134:in `partitions_for'
/Library/Ruby/Gems/2.6.0/gems/ruby-kafka-1.2.0/lib/kafka/protocol.rb:160:in `handle_error': Kafka::InvalidReplicationFactor (Kafka::InvalidReplicationFactor)
```

I used telnet and confirmed that the Kafka Broker is running. Describing the topic gives me this:

```

devops@kafka:~/kafka_2.12-2.5.0$ bin/kafka-topics.sh --describe --zookeeper localhost:2181 --topic rsil
Topic: rsil     PartitionCount: 1       ReplicationFactor: 1    Configs: 
        Topic: rsil     Partition: 0    Leader: none    Replicas: 0     Isr: 
```

**Comment by rishabhsinghvi** [comment]
I seem to have fixed the issue, using the following steps.


1) Stop the server.
2) Delete the `meta.properties` file in the `/tmp/kafka_logs` directory.
3) Restart the server.

Still not sure what the problem was, but seems like it's fixed.
